# Generated by Django 3.2.15 on 2025-03-20 11:28

from django.db import migrations, models

import bkflow.bk_plugin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalPlugin",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="插件ID")),
                ("name", models.CharField(max_length=255, verbose_name="插件名称")),
                ("admin", models.CharField(max_length=100, verbose_name="管理员名称")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (bkflow.bk_plugin.models.AuthStatus["authorized"], "已授权"),
                            (bkflow.bk_plugin.models.AuthStatus["unauthorized"], "未授权"),
                        ],
                        default=bkflow.bk_plugin.models.AuthStatus["unauthorized"],
                        verbose_name="授权状态",
                    ),
                ),
                ("scope", models.JSONField(default=list, verbose_name="使用范围")),
                ("authorized_time", models.DateTimeField(blank=True, null=True, verbose_name="授权时间")),
                ("operator", models.CharField(blank=True, default="", max_length=100, verbose_name="授权人")),
            ],
            options={
                "verbose_name": "蓝鲸插件授权信息",
                "verbose_name_plural": "蓝鲸插件授权信息表",
            },
        ),
    ]
