# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸流程引擎服务 (BlueKing Flow Engine Service) available.
Copyright (C) 2024 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.15 on 2025-03-20 11:28

from django.db import migrations, models

import bkflow.bk_plugin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocalPlugin",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False, verbose_name="插件ID")),
                ("name", models.CharField(max_length=255, verbose_name="插件名称")),
                ("admin", models.CharField(max_length=100, verbose_name="管理员名称")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (bkflow.bk_plugin.models.AuthStatus["authorized"], "已授权"),
                            (bkflow.bk_plugin.models.AuthStatus["unauthorized"], "未授权"),
                        ],
                        default=bkflow.bk_plugin.models.AuthStatus["unauthorized"],
                        verbose_name="授权状态",
                    ),
                ),
                ("scope", models.JSONField(default=list, verbose_name="使用范围")),
                ("authorized_time", models.DateTimeField(blank=True, null=True, verbose_name="授权时间")),
                ("operator", models.CharField(blank=True, default="", max_length=100, verbose_name="授权人")),
            ],
            options={
                "verbose_name": "蓝鲸插件授权信息",
                "verbose_name_plural": "蓝鲸插件授权信息表",
            },
        ),
    ]
