# Generated by Django 3.2.15 on 2025-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="localplugin",
            name="code",
            field=models.CharField(default="bk_default", max_length=255, verbose_name="插件code"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localplugin",
            name="tag",
            field=models.IntegerField(default=-1, verbose_name="插件隶属分类"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="localplugin",
            name="updated",
            field=models.DateTimeField(blank=True, null=True, verbose_name="上次更新时间"),
        ),
    ]
