# Generated by Django 3.2.25 on 2026-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bkplugin",
            name="tenant_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64, verbose_name="插件所属租户"),
        ),
    ]
