# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸流程引擎服务 (BlueKing Flow Engine Service) available.
Copyright (C) 2024 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.15 on 2025-03-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0002_auto_20250321_1133"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localplugin",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="id",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="name",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="updated",
        ),
        migrations.AddField(
            model_name="localplugin",
            name="extra_info",
            field=models.JSONField(default=dict, verbose_name="插件其他信息"),
        ),
        migrations.AddField(
            model_name="localplugin",
            name="managers",
            field=models.JSONField(default=list, verbose_name="管理员名称"),
        ),
        migrations.AddField(
            model_name="localplugin",
            name="white_list",
            field=models.JSONField(default=dict, verbose_name="使用范围"),
        ),
        migrations.AlterField(
            model_name="localplugin",
            name="code",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="插件code"),
        ),
        migrations.AlterField(
            model_name="localplugin",
            name="tag",
            field=models.IntegerField(db_index=True, verbose_name="插件隶属分类"),
        ),
    ]
