# Generated by Django 3.2.15 on 2025-03-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0002_auto_20250321_1133"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localplugin",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="id",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="name",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="scope",
        ),
        migrations.RemoveField(
            model_name="localplugin",
            name="updated",
        ),
        migrations.AddField(
            model_name="localplugin",
            name="extra_info",
            field=models.JSONField(default=dict, verbose_name="插件其他信息"),
        ),
        migrations.AddField(
            model_name="localplugin",
            name="managers",
            field=models.JSONField(default=list, verbose_name="管理员名称"),
        ),
        migrations.AddField(
            model_name="localplugin",
            name="white_list",
            field=models.JSONField(default=dict, verbose_name="使用范围"),
        ),
        migrations.AlterField(
            model_name="localplugin",
            name="code",
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name="插件code"),
        ),
        migrations.AlterField(
            model_name="localplugin",
            name="tag",
            field=models.IntegerField(db_index=True, verbose_name="插件隶属分类"),
        ),
    ]
