# Generated by Django 3.2.15 on 2025-03-26 08:38

from django.db import migrations, models

import bkflow.bk_plugin.models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0004_auto_20250324_1449"),
    ]

    operations = [
        migrations.CreateModel(
            name="BKPluginAuthentication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, verbose_name="插件code")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (bkflow.bk_plugin.models.AuthStatus["authorized"], "已授权"),
                            (bkflow.bk_plugin.models.AuthStatus["unauthorized"], "未授权"),
                        ],
                        default=bkflow.bk_plugin.models.AuthStatus["unauthorized"],
                        verbose_name="授权状态",
                    ),
                ),
                ("authorized_time", models.DateTimeField(blank=True, null=True, verbose_name="授权时间")),
                (
                    "config",
                    models.JSONField(default=bkflow.bk_plugin.models.get_default_config, verbose_name="授权配置，如使用范围等"),
                ),
                ("operator", models.CharField(blank=True, default="", max_length=100, verbose_name="授权人名称")),
            ],
            options={
                "verbose_name": "蓝鲸插件授权记录",
                "verbose_name_plural": "蓝鲸插件授权记录表",
            },
        ),
        migrations.AlterModelOptions(
            name="bkplugin",
            options={"verbose_name": "蓝鲸插件", "verbose_name_plural": "蓝鲸插件实时信息表"},
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="authorized_time",
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="config",
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="managers",
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="operator",
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="status",
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="contact",
            field=models.CharField(default="", max_length=255, verbose_name="联系人，以逗号分隔"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="created_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="创建时间"),
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="introduction",
            field=models.CharField(default="", max_length=255, verbose_name="插件简介"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="logo_url",
            field=models.CharField(default="", max_length=255, verbose_name="插件图片url"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="插件名称"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="updated_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="bkplugin",
            name="code",
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name="插件code"),
        ),
        migrations.AlterField(
            model_name="bkplugin",
            name="extra_info",
            field=models.JSONField(default=dict, verbose_name="额外信息"),
        ),
    ]
