# Generated by Django 3.2.15 on 2025-03-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0005_auto_20250326_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bkpluginauthentication",
            name="code",
            field=models.CharField(db_index=True, max_length=100, verbose_name="插件code"),
        ),
    ]
