# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸流程引擎服务 (BlueKing Flow Engine Service) available.
Copyright (C) 2024 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.15 on 2025-03-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0006_alter_bkpluginauthentication_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bkplugin",
            options={"verbose_name": "蓝鲸插件", "verbose_name_plural": "蓝鲸插件"},
        ),
        migrations.AlterModelOptions(
            name="bkpluginauthentication",
            options={"verbose_name": "蓝鲸插件授权记录", "verbose_name_plural": "蓝鲸插件授权记录"},
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="contact",
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="manager",
            field=models.JSONField(default=list, verbose_name="插件管理员列表"),
        ),
    ]
