# Generated by Django 3.2.15 on 2025-03-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0006_alter_bkpluginauthentication_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bkplugin",
            options={"verbose_name": "蓝鲸插件", "verbose_name_plural": "蓝鲸插件"},
        ),
        migrations.AlterModelOptions(
            name="bkpluginauthentication",
            options={"verbose_name": "蓝鲸插件授权记录", "verbose_name_plural": "蓝鲸插件授权记录"},
        ),
        migrations.RemoveField(
            model_name="bkplugin",
            name="contact",
        ),
        migrations.AddField(
            model_name="bkplugin",
            name="manager",
            field=models.JSONField(default=list, verbose_name="插件管理员列表"),
        ),
    ]
