# Generated by Django 3.2.15 on 2025-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bk_plugin", "0007_auto_20250328_1138"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BKPluginAuthentication",
            new_name="BKPluginAuthorization",
        ),
    ]
