# Generated by Django 3.2.25 on 2026-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VariableManager",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("space_id", models.BigIntegerField(verbose_name="空间 ID")),
                ("name", models.CharField(max_length=255, verbose_name="变量名")),
                ("type", models.CharField(max_length=255, verbose_name="变量类型")),
                ("key", models.CharField(max_length=255, verbose_name="变量唯一键")),
                ("value", models.TextField(verbose_name="变量值")),
                ("desc", models.TextField(verbose_name="变量描述")),
            ],
            options={
                "unique_together": {("space_id", "key")},
            },
        ),
    ]
