# Generated by Django 3.2.25 on 2026-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variable_manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variablemanager",
            old_name="type",
            new_name="variable_type",
        ),
        migrations.AlterField(
            model_name="variablemanager",
            name="desc",
            field=models.TextField(blank=True, null=True, verbose_name="变量描述"),
        ),
    ]
