# Generated by Django 3.2.25 on 2026-09-09 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0004_alter_token_expired_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenGrant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("resource_type", models.CharField(max_length=32, verbose_name="资源类型")),
                ("resource_id", models.CharField(max_length=32, verbose_name="资源ID")),
                (
                    "permission_type",
                    models.CharField(
                        choices=[("VIEW", "查看"), ("EDIT", "编辑"), ("OPERATE", "操作"), ("MOCK", "调试")],
                        max_length=32,
                        verbose_name="权限类型",
                    ),
                ),
                ("grant_hash", models.CharField(max_length=64, verbose_name="授权摘要")),
            ],
            options={
                "verbose_name": "token 授权明细",
                "verbose_name_plural": "token 授权明细",
            },
        ),
        migrations.AddField(
            model_name="token",
            name="grant_set_hash",
            field=models.CharField(max_length=64, null=True, verbose_name="授权集合摘要"),
        ),
        migrations.AddIndex(
            model_name="token",
            index=models.Index(
                fields=["space_id", "user", "grant_set_hash", "expired_time"], name="perm_tok_s_u_g_exp_idx"
            ),
        ),
        migrations.AddField(
            model_name="tokengrant",
            name="token",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grants",
                to="permission.token",
                verbose_name="Token",
            ),
        ),
        migrations.AddIndex(
            model_name="tokengrant",
            index=models.Index(
                fields=["resource_type", "resource_id", "permission_type", "token"], name="perm_grant_res_perm_tok_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tokengrant",
            constraint=models.UniqueConstraint(fields=("token", "grant_hash"), name="perm_grant_tok_hash_uniq"),
        ),
    ]
