"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸流程引擎服务 (BlueKing Flow Engine Service) available.
Copyright (C) 2024 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.25 on 2026-09-09 07:16

import hashlib
import json

from django.db import migrations

RESOURCE_TYPES = {"TASK", "TEMPLATE", "SCOPE", "LABEL"}
PERMISSION_TYPES = {"VIEW", "EDIT", "OPERATE", "MOCK"}


def payload_hash(payload):
    """使用冻结的 v1 紧凑 JSON 协议计算摘要。"""
    serialized = json.dumps(payload, ensure_ascii=True, separators=(",", ":"))
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def item_digest(fields):
    """计算一项历史授权的冻结摘要。"""
    return payload_hash(["v1", *fields])


def set_digest(fields_collection):
    """计算已排序授权集合的冻结摘要。"""
    return payload_hash(["v1", [list(fields) for fields in sorted(fields_collection)]])


def _validate_runtime_fields(fields):
    """验证原生组合明细能否成为运行时有效授权。"""
    if any(not isinstance(field, str) or not field or len(field) > 32 for field in fields):
        raise RuntimeError("Token grant migration found invalid grant fields")
    if fields[0] not in RESOURCE_TYPES or fields[2] not in PERMISSION_TYPES:
        raise RuntimeError("Token grant migration found unsupported grant fields")


def _validated_details(TokenGrant, db_alias, token):
    """读取并验证一张票据的明细身份、唯一性和摘要。"""
    details = list(TokenGrant.objects.using(db_alias).filter(token_id=token.pk).order_by("pk"))
    fields_collection = []
    hashes = set()
    for detail in details:
        if detail.token_id != token.pk:
            raise RuntimeError("Token grant migration found mismatched detail owner")
        fields = (detail.resource_type, detail.resource_id, detail.permission_type)
        if detail.grant_hash != item_digest(fields):
            raise RuntimeError("Token grant migration found an inconsistent item digest")
        if fields in fields_collection or detail.grant_hash in hashes:
            raise RuntimeError("Token grant migration found duplicate grant details")
        fields_collection.append(fields)
        hashes.add(detail.grant_hash)
    canonical = tuple(sorted(fields_collection))
    if not canonical or token.grant_set_hash != set_digest(canonical):
        raise RuntimeError("Token grant migration found an inconsistent grant set")
    return canonical


def _validate_backfilled_or_composite(TokenGrant, db_alias, token):
    """区分精确回填单项与旧列为空的原生组合票据。"""
    canonical = _validated_details(TokenGrant, db_alias, token)
    legacy_fields = (token.resource_type, token.resource_id, token.permission_type)
    if len(canonical) == 1:
        if canonical != (legacy_fields,):
            raise RuntimeError("Token grant migration found a non-idempotent single grant")
        if not any(legacy_fields):
            raise RuntimeError("Token grant migration found an empty legacy grant")
        return canonical
    if any(legacy_fields):
        raise RuntimeError("Token grant migration found legacy fields on a composite grant")
    for fields in canonical:
        _validate_runtime_fields(fields)
    return canonical


def forwards(apps, schema_editor):
    """回填所有历史单项，并在任何写入前拒绝损坏组合票据。"""
    Token = apps.get_model("permission", "Token")
    TokenGrant = apps.get_model("permission", "TokenGrant")
    db_alias = schema_editor.connection.alias
    tokens = list(Token.objects.using(db_alias).select_for_update().order_by("pk"))

    for token in tokens:
        if token.grant_set_hash is not None:
            _validate_backfilled_or_composite(TokenGrant, db_alias, token)

    for token in tokens:
        if token.grant_set_hash is not None:
            continue
        fields = (token.resource_type, token.resource_id, token.permission_type)
        if not any(fields):
            raise RuntimeError("Token grant migration found an empty legacy grant")
        TokenGrant.objects.using(db_alias).filter(token_id=token.pk).delete()
        TokenGrant.objects.using(db_alias).create(
            token_id=token.pk,
            resource_type=fields[0],
            resource_id=fields[1],
            permission_type=fields[2],
            grant_hash=item_digest(fields),
        )
        token.grant_set_hash = set_digest((fields,))
        token.save(using=db_alias, update_fields=["grant_set_hash"])
        _validate_backfilled_or_composite(TokenGrant, db_alias, token)


def backwards(apps, schema_editor):
    """将有效单项还原到旧列，保留有效组合的摘要与明细。"""
    Token = apps.get_model("permission", "Token")
    TokenGrant = apps.get_model("permission", "TokenGrant")
    db_alias = schema_editor.connection.alias
    tokens = list(Token.objects.using(db_alias).select_for_update().order_by("pk"))
    collections = []

    for token in tokens:
        if token.grant_set_hash is None:
            raise RuntimeError("Token grant reverse migration found a missing grant set digest")
        canonical = _validated_details(TokenGrant, db_alias, token)
        if len(canonical) == 1:
            if not any(canonical[0]):
                raise RuntimeError("Token grant reverse migration found an empty single grant")
        else:
            for fields in canonical:
                _validate_runtime_fields(fields)
        collections.append((token, canonical))

    for token, canonical in collections:
        if len(canonical) == 1:
            fields = canonical[0]
            token.resource_type, token.resource_id, token.permission_type = fields
            token.grant_set_hash = None
            token.save(
                using=db_alias,
                update_fields=["resource_type", "resource_id", "permission_type", "grant_set_hash"],
            )
            TokenGrant.objects.using(db_alias).filter(token_id=token.pk).delete()
        else:
            token.resource_type = token.resource_id = token.permission_type = ""
            token.save(using=db_alias, update_fields=["resource_type", "resource_id", "permission_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0005_auto_20260909_1147"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards, atomic=True),
    ]
