# Generated by Django 3.2.25 on 2026-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permission", "0006_backfill_token_grants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="grant_set_hash",
            field=models.CharField(max_length=64, verbose_name="授权集合摘要"),
        ),
        migrations.AlterIndexTogether(
            name="token",
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name="token",
            name="permission_type",
        ),
        migrations.RemoveField(
            model_name="token",
            name="resource_id",
        ),
        migrations.RemoveField(
            model_name="token",
            name="resource_type",
        ),
    ]
