# Generated by Django 3.2.15 on 2026-04-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPluginCatalogIndex",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间ID")),
                ("source_key", models.CharField(max_length=64, verbose_name="开放插件来源")),
                ("plugin_id", models.CharField(max_length=128, verbose_name="开放插件ID")),
                ("plugin_code", models.CharField(max_length=128, verbose_name="插件编码")),
                ("plugin_name", models.CharField(max_length=255, verbose_name="插件名称")),
                ("plugin_source", models.CharField(max_length=64, verbose_name="插件来源类型")),
                ("group_name", models.CharField(blank=True, default="", max_length=128, verbose_name="插件分组")),
                ("wrapper_version", models.CharField(blank=True, default="", max_length=32, verbose_name="包装器版本")),
                ("default_version", models.CharField(blank=True, default="", max_length=64, verbose_name="默认业务版本")),
                ("latest_version", models.CharField(blank=True, default="", max_length=64, verbose_name="最新业务版本")),
                ("versions", models.JSONField(blank=True, default=list, verbose_name="可用业务版本列表")),
                (
                    "meta_url_template",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="插件详情模板URL"),
                ),
                ("description", models.TextField(blank=True, default="", verbose_name="插件描述")),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "available"), ("unavailable", "unavailable")],
                        default="available",
                        max_length=32,
                        verbose_name="插件状态",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "开放插件目录索引",
                "verbose_name_plural": "开放插件目录索引",
                "unique_together": {("space_id", "source_key", "plugin_id")},
            },
        ),
        migrations.CreateModel(
            name="SpaceOpenPluginAvailability",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间ID")),
                ("source_key", models.CharField(max_length=64, verbose_name="开放插件来源")),
                ("plugin_id", models.CharField(max_length=128, verbose_name="开放插件ID")),
                ("enabled", models.BooleanField(default=False, verbose_name="是否已开启")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "空间开放插件可用性",
                "verbose_name_plural": "空间开放插件可用性",
                "unique_together": {("space_id", "source_key", "plugin_id")},
            },
        ),
        migrations.AddIndex(
            model_name="openplugincatalogindex",
            index=models.Index(fields=["space_id", "source_key"], name="plugin_open_space_i_7102c4_idx"),
        ),
        migrations.AddIndex(
            model_name="openplugincatalogindex",
            index=models.Index(fields=["space_id", "status"], name="plugin_open_space_i_2c81d6_idx"),
        ),
        migrations.AddIndex(
            model_name="spaceopenpluginavailability",
            index=models.Index(
                fields=["space_id", "source_key", "enabled"],
                name="plugin_spaceopen_space_i_14dab4_idx",
            ),
        ),
    ]
