# Generated by Django 3.2.15 on 2026-04-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0002_open_plugin_catalog_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPluginRunCallbackRef",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.BigIntegerField(db_index=True, verbose_name="任务ID")),
                ("node_id", models.CharField(db_index=True, max_length=64, verbose_name="节点ID")),
                ("node_version", models.CharField(blank=True, default="", max_length=32, verbose_name="节点版本")),
                ("client_request_id", models.CharField(max_length=128, unique=True, verbose_name="客户端请求ID")),
                (
                    "open_plugin_run_id",
                    models.CharField(db_index=True, max_length=64, unique=True, verbose_name="开放插件运行ID"),
                ),
                ("callback_token_digest", models.CharField(max_length=128, verbose_name="回调令牌摘要")),
                ("callback_expire_at", models.DateTimeField(verbose_name="回调令牌过期时间")),
                ("plugin_source", models.CharField(blank=True, default="", max_length=64, verbose_name="插件来源类型")),
                ("source_key", models.CharField(blank=True, default="", max_length=64, verbose_name="开放插件来源")),
                ("plugin_id", models.CharField(max_length=128, verbose_name="开放插件ID")),
                ("plugin_version", models.CharField(blank=True, default="", max_length=64, verbose_name="开放插件版本")),
                ("cancel_url", models.CharField(blank=True, default="", max_length=1024, verbose_name="开放插件取消URL")),
                ("credential_key", models.CharField(blank=True, default="", max_length=128, verbose_name="取消调用使用的凭证key")),
                ("consumed_at", models.DateTimeField(blank=True, null=True, verbose_name="回调消费时间")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "开放插件回调映射",
                "verbose_name_plural": "开放插件回调映射",
            },
        ),
        migrations.AddIndex(
            model_name="openpluginruncallbackref",
            index=models.Index(fields=["task_id", "node_id"], name="plugin_open_task_id_7a46d7_idx"),
        ),
        migrations.AddIndex(
            model_name="openpluginruncallbackref",
            index=models.Index(fields=["callback_expire_at"], name="plugin_open_callbac_89b01d_idx"),
        ),
    ]
