# Generated by Django 3.2.25 on 2026-06-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0003_openpluginruncallbackref"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenPluginSpaceGrant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间ID")),
                ("source_key", models.CharField(max_length=64, verbose_name="开放插件来源")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否准入")),
                ("operator", models.CharField(blank=True, default="", max_length=64, verbose_name="操作人")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "空间开放插件来源准入",
                "verbose_name_plural": "空间开放插件来源准入",
            },
        ),
        migrations.AddIndex(
            model_name="openpluginspacegrant",
            index=models.Index(fields=["space_id", "source_key", "enabled"], name="plugin_open_space_i_6a5a4b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="openpluginspacegrant",
            unique_together={("space_id", "source_key")},
        ),
    ]
