# Generated by Codex on 2026-06-26

from django.db import migrations


def forwards(apps, schema_editor):
    from bkflow.plugin.services.open_plugin_grant import OpenPluginGrantService

    OpenPluginGrantService.backfill_existing_sources()


def backwards(apps, schema_editor):
    OpenPluginSpaceGrant = apps.get_model("plugin", "OpenPluginSpaceGrant")
    OpenPluginSpaceGrant.objects.filter(operator="migration").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0004_open_plugin_space_grant"),
        ("space", "0004_alter_spaceconfig_json_value"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
