# Generated by Django 3.2.25 on 2026-07-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0005_backfill_open_plugin_grant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OpenPluginRunCallbackRef",
        ),
    ]
