# Generated by Django 3.2.25 on 2026-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugin", "0006_remove_open_plugin_run_callback_ref"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="spaceopenpluginavailability",
            name="plugin_spaceopen_space_i_14dab4_idx",
        ),
        migrations.AddField(
            model_name="openplugincatalogindex",
            name="group_display_name",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="插件分组展示名"),
        ),
        migrations.AddIndex(
            model_name="spaceopenpluginavailability",
            index=models.Index(fields=["space_id", "source_key", "enabled"], name="plugin_spac_space_i_d7bb9f_idx"),
        ),
    ]
