# Generated by Django 3.2.15 on 2025-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0004_auto_20240823_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("space_id", models.IntegerField(help_text="Space ID")),
                ("template_id", models.IntegerField(db_index=True, help_text="Related template ID")),
                ("is_enabled", models.BooleanField(default=True, help_text="Indicates whether the trigger is enabled")),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(help_text="Configuration for the trigger")),
                (
                    "type",
                    models.CharField(
                        choices=[("periodic", "定时"), ("remote", "远程")],
                        default="periodic",
                        help_text="Type of the trigger",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="trigger",
            index=models.Index(fields=["space_id", "template_id"], name="template_tr_space_i_0cf8a3_idx"),
        ),
    ]
