# Generated by Django 3.2.25 on 2025-09-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0005_auto_20250815_1921"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("root_template_id", models.CharField(db_index=True, max_length=32, verbose_name="主流程模板ID")),
                ("subprocess_template_id", models.CharField(db_index=True, max_length=32, verbose_name="子流程模板ID")),
                ("subprocess_node_id", models.CharField(max_length=32, verbose_name="子流程节点 ID")),
                ("version", models.CharField(max_length=32, verbose_name="快照字符串的md5")),
                ("always_use_latest", models.BooleanField(default=False, verbose_name="是否永远使用最新版本")),
            ],
        ),
        migrations.RemoveField(
            model_name="template",
            name="version",
        ),
        migrations.AlterField(
            model_name="templateoperationrecord",
            name="operate_source",
            field=models.CharField(
                choices=[("app", "app 页面"), ("api", "api 接口"), ("parent", "父任务")], max_length=64, verbose_name="操作来源"
            ),
        ),
    ]
