# Generated by Django 3.2.25 on 2025-10-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0006_auto_20250916_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatesnapshot",
            name="creator",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="创建人"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="desc",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="描述"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="draft",
            field=models.BooleanField(default=False, verbose_name="是否草稿"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否删除"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="operator",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="操作人"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="version",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="版本号"),
        ),
    ]
