# Generated by Django 3.2.25 on 2025-10-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0006_auto_20250916_1625"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatesnapshot",
            name="draft",
            field=models.BooleanField(default=False, verbose_name="是否草稿"),
        ),
        migrations.AddField(
            model_name="templatesnapshot",
            name="version",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="版本号"),
        ),
    ]
