# Generated by Django 3.2.25 on 2025-11-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0007_auto_20251028_1650"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatesnapshot",
            name="version",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name="版本号"),
        ),
    ]
