# Generated by Django 3.2.25 on 2026-06-26 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0010_template_add_bk_app_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugContext",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("template_id", models.BigIntegerField(unique=True, verbose_name="模板ID")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间ID")),
                ("global_vars", models.JSONField(blank=True, default=dict, verbose_name="调试全局变量")),
                ("tree_fingerprint", models.JSONField(blank=True, default=dict, verbose_name="树指纹")),
                (
                    "status",
                    models.CharField(
                        choices=[("idle", "idle"), ("running", "running"), ("terminating", "terminating")],
                        default="idle",
                        max_length=16,
                        verbose_name="调试状态",
                    ),
                ),
                ("active_task_id", models.BigIntegerField(blank=True, null=True, verbose_name="当前DEBUG任务ID")),
                ("last_inputs", models.JSONField(blank=True, default=dict, verbose_name="最近一次输入")),
                ("locked_by", models.CharField(blank=True, default="", max_length=32, verbose_name="持锁用户")),
                ("locked_at", models.DateTimeField(blank=True, null=True, verbose_name="持锁时间")),
            ],
            options={
                "verbose_name": "调试上下文 DebugContext",
                "verbose_name_plural": "调试上下文 DebugContext",
            },
        ),
        migrations.CreateModel(
            name="DebugNodeState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=33, verbose_name="节点ID")),
                ("node_type", models.CharField(default="ServiceActivity", max_length=32, verbose_name="节点类型")),
                (
                    "execution_mode",
                    models.CharField(
                        choices=[("real", "real"), ("mock", "mock")], default="real", max_length=8, verbose_name="执行模式"
                    ),
                ),
                (
                    "mock_result",
                    models.CharField(
                        choices=[("success", "success"), ("fail", "fail")],
                        default="success",
                        max_length=8,
                        verbose_name="Mock结果",
                    ),
                ),
                ("mock_outputs", models.JSONField(blank=True, default=dict, verbose_name="Mock预设输出")),
                ("mock_error", models.CharField(blank=True, default="", max_length=1024, verbose_name="Mock错误信息")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_run", "not_run"),
                            ("running", "running"),
                            ("finished", "finished"),
                            ("failed", "failed"),
                        ],
                        default="not_run",
                        max_length=16,
                        verbose_name="运行状态",
                    ),
                ),
                ("inputs", models.JSONField(blank=True, default=dict, verbose_name="最近输入快照")),
                ("outputs", models.JSONField(blank=True, default=dict, verbose_name="最近输出快照")),
                ("duration_ms", models.IntegerField(blank=True, null=True, verbose_name="耗时(ms)")),
                ("error_detail", models.JSONField(blank=True, default=dict, verbose_name="错误详情")),
                ("log_ref", models.JSONField(blank=True, default=dict, verbose_name="引擎引用")),
                ("config_hash", models.CharField(blank=True, default="", max_length=64, verbose_name="配置指纹")),
                ("last_run_at", models.DateTimeField(blank=True, null=True, verbose_name="最近运行时间")),
                (
                    "debug_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_states",
                        to="template.debugcontext",
                        verbose_name="所属上下文",
                    ),
                ),
            ],
            options={
                "verbose_name": "调试节点态 DebugNodeState",
                "verbose_name_plural": "调试节点态 DebugNodeState",
                "unique_together": {("debug_context", "node_id")},
            },
        ),
    ]
