# Generated by Django 3.2.25 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0011_debugcontext_debugnodestate"),
    ]

    operations = [
        migrations.AddField(
            model_name="debugcontext",
            name="active_node_id",
            field=models.CharField(blank=True, default="", max_length=33, verbose_name="当前单步节点ID"),
        ),
        migrations.AddField(
            model_name="debugcontext",
            name="active_run_type",
            field=models.CharField(
                blank=True,
                choices=[("global", "global"), ("step", "step")],
                default="",
                max_length=16,
                verbose_name="当前调试类型",
            ),
        ),
        migrations.AddField(
            model_name="debugcontext",
            name="last_error_detail",
            field=models.JSONField(blank=True, default=dict, verbose_name="最近调试错误详情"),
        ),
        migrations.AddField(
            model_name="debugcontext",
            name="last_run_status",
            field=models.CharField(
                choices=[
                    ("not_run", "not_run"),
                    ("running", "running"),
                    ("waiting", "waiting"),
                    ("paused", "paused"),
                    ("finished", "finished"),
                    ("failed", "failed"),
                    ("revoked", "revoked"),
                ],
                default="not_run",
                max_length=16,
                verbose_name="最近调试状态",
            ),
        ),
        migrations.AddField(
            model_name="debugcontext",
            name="last_run_type",
            field=models.CharField(
                blank=True,
                choices=[("global", "global"), ("step", "step")],
                default="",
                max_length=16,
                verbose_name="最近调试类型",
            ),
        ),
        migrations.AddField(
            model_name="debugcontext",
            name="last_task_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="最近DEBUG任务ID"),
        ),
        migrations.AddField(
            model_name="debugnodestate",
            name="waiting_reason",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="等待原因"),
        ),
        migrations.AlterField(
            model_name="debugnodestate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_run", "not_run"),
                    ("running", "running"),
                    ("waiting", "waiting"),
                    ("paused", "paused"),
                    ("finished", "finished"),
                    ("failed", "failed"),
                ],
                default="not_run",
                max_length=16,
                verbose_name="运行状态",
            ),
        ),
    ]
