# Generated by Django 3.2.25 on 2026-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0012_debug_run_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debugnodestate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_run", "not_run"),
                    ("running", "running"),
                    ("waiting", "waiting"),
                    ("paused", "paused"),
                    ("finished", "finished"),
                    ("failed", "failed"),
                    ("revoked", "revoked"),
                ],
                default="not_run",
                max_length=16,
                verbose_name="运行状态",
            ),
        ),
    ]
