# Generated by Django 3.2.25 on 2026-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStatisticsSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True, verbose_name="统计日期")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("scope_type", models.CharField(default="", max_length=64, verbose_name="范围类型")),
                ("scope_value", models.CharField(default="", max_length=255, verbose_name="范围值")),
                ("task_created_count", models.IntegerField(default=0, verbose_name="创建任务数")),
                ("task_finished_count", models.IntegerField(default=0, verbose_name="完成任务数")),
                ("task_success_count", models.IntegerField(default=0, verbose_name="成功任务数")),
                ("task_failed_count", models.IntegerField(default=0, verbose_name="失败任务数")),
                ("task_revoked_count", models.IntegerField(default=0, verbose_name="撤销任务数")),
                ("node_executed_count", models.IntegerField(default=0, verbose_name="执行节点数")),
                ("node_success_count", models.IntegerField(default=0, verbose_name="成功节点数")),
                ("node_failed_count", models.IntegerField(default=0, verbose_name="失败节点数")),
                ("avg_task_elapsed_time", models.FloatField(default=0, verbose_name="平均任务耗时(秒)")),
                ("max_task_elapsed_time", models.IntegerField(default=0, verbose_name="最大任务耗时(秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="记录更新时间")),
            ],
            options={
                "verbose_name": "每日统计汇总",
                "verbose_name_plural": "每日统计汇总",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PluginExecutionSummary",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("period_type", models.CharField(db_index=True, max_length=16, verbose_name="周期类型")),
                ("period_start", models.DateField(db_index=True, verbose_name="周期开始日期")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("component_code", models.CharField(db_index=True, max_length=255, verbose_name="组件编码")),
                ("version", models.CharField(default="legacy", max_length=255, verbose_name="插件版本")),
                ("is_remote", models.BooleanField(default=False, verbose_name="是否第三方插件")),
                ("execution_count", models.IntegerField(default=0, verbose_name="执行次数")),
                ("success_count", models.IntegerField(default=0, verbose_name="成功次数")),
                ("failed_count", models.IntegerField(default=0, verbose_name="失败次数")),
                ("avg_elapsed_time", models.FloatField(default=0, verbose_name="平均耗时(秒)")),
                ("max_elapsed_time", models.IntegerField(default=0, verbose_name="最大耗时(秒)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="记录更新时间")),
            ],
            options={
                "verbose_name": "插件执行汇总",
                "verbose_name_plural": "插件执行汇总",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskflowExecutedNodeStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_id", models.BigIntegerField(db_index=True, verbose_name="任务ID")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("engine_id", models.CharField(default="", max_length=64, verbose_name="Engine标识")),
                ("component_code", models.CharField(db_index=True, max_length=255, verbose_name="组件编码")),
                ("version", models.CharField(default="legacy", max_length=255, verbose_name="插件版本")),
                ("is_remote", models.BooleanField(default=False, verbose_name="是否第三方插件")),
                ("node_id", models.CharField(max_length=64, verbose_name="节点ID")),
                ("started_time", models.DateTimeField(db_index=True, verbose_name="执行开始时间")),
                ("archived_time", models.DateTimeField(blank=True, null=True, verbose_name="执行结束时间")),
                ("elapsed_time", models.IntegerField(blank=True, null=True, verbose_name="耗时(秒)")),
                ("status", models.BooleanField(default=False, verbose_name="执行结果")),
                ("state", models.CharField(default="", max_length=32, verbose_name="节点状态")),
                ("is_skip", models.BooleanField(default=False, verbose_name="是否跳过")),
                ("is_retry", models.BooleanField(default=False, verbose_name="是否重试记录")),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
            ],
            options={
                "verbose_name": "节点执行统计",
                "verbose_name_plural": "节点执行统计",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskflowStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("task_id", models.BigIntegerField(db_index=True, unique=True, verbose_name="任务ID")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("scope_type", models.CharField(default="", max_length=64, verbose_name="范围类型")),
                ("scope_value", models.CharField(default="", max_length=255, verbose_name="范围值")),
                ("template_id", models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name="关联模板ID")),
                ("engine_id", models.CharField(db_index=True, default="", max_length=64, verbose_name="Engine标识")),
                ("atom_total", models.IntegerField(default=0, verbose_name="标准插件节点总数")),
                ("subprocess_total", models.IntegerField(default=0, verbose_name="子流程节点总数")),
                ("gateways_total", models.IntegerField(default=0, verbose_name="网关节点总数")),
                ("create_time", models.DateTimeField(db_index=True, verbose_name="任务创建时间")),
                ("start_time", models.DateTimeField(blank=True, null=True, verbose_name="启动时间")),
                ("finish_time", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("elapsed_time", models.IntegerField(blank=True, null=True, verbose_name="执行耗时(秒)")),
                ("is_started", models.BooleanField(default=False, verbose_name="是否已启动")),
                ("is_finished", models.BooleanField(default=False, verbose_name="是否已完成")),
                ("final_state", models.CharField(db_index=True, default="CREATED", max_length=32, verbose_name="最终状态")),
                ("create_method", models.CharField(default="API", max_length=32, verbose_name="创建方式")),
                ("trigger_method", models.CharField(default="manual", max_length=32, verbose_name="触发方式")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="记录更新时间")),
            ],
            options={
                "verbose_name": "任务统计",
                "verbose_name_plural": "任务统计",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateNodeStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("component_code", models.CharField(db_index=True, max_length=255, verbose_name="组件编码")),
                ("version", models.CharField(default="legacy", max_length=255, verbose_name="插件版本")),
                ("is_remote", models.BooleanField(default=False, verbose_name="是否第三方插件")),
                ("template_id", models.BigIntegerField(db_index=True, verbose_name="模板ID")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("scope_type", models.CharField(default="", max_length=64, verbose_name="范围类型")),
                ("scope_value", models.CharField(default="", max_length=255, verbose_name="范围值")),
                ("node_id", models.CharField(max_length=64, verbose_name="节点ID")),
                ("node_name", models.CharField(default="", max_length=255, verbose_name="节点名称")),
                ("is_sub", models.BooleanField(default=False, verbose_name="是否子流程内引用")),
                ("subprocess_stack", models.TextField(default="[]", verbose_name="子流程堆栈")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
            ],
            options={
                "verbose_name": "模板节点统计",
                "verbose_name_plural": "模板节点统计",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateStatistics",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("template_id", models.BigIntegerField(db_index=True, unique=True, verbose_name="模板ID")),
                ("space_id", models.BigIntegerField(db_index=True, verbose_name="空间ID")),
                ("scope_type", models.CharField(default="", max_length=64, verbose_name="范围类型")),
                ("scope_value", models.CharField(default="", max_length=255, verbose_name="范围值")),
                ("atom_total", models.IntegerField(default=0, verbose_name="标准插件节点总数")),
                ("subprocess_total", models.IntegerField(default=0, verbose_name="子流程节点总数")),
                ("gateways_total", models.IntegerField(default=0, verbose_name="网关节点总数")),
                ("template_name", models.CharField(default="", max_length=255, verbose_name="模板名称")),
                ("is_enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                ("template_create_time", models.DateTimeField(null=True, verbose_name="模板创建时间")),
                ("template_update_time", models.DateTimeField(null=True, verbose_name="模板更新时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="记录创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="记录更新时间")),
            ],
            options={
                "verbose_name": "模板统计",
                "verbose_name_plural": "模板统计",
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="templatenodestatistics",
            index=models.Index(fields=["space_id", "component_code"], name="statistics__space_i_a07edd_idx"),
        ),
        migrations.AddIndex(
            model_name="templatenodestatistics",
            index=models.Index(fields=["template_id", "node_id"], name="statistics__templat_89a932_idx"),
        ),
        migrations.AddIndex(
            model_name="taskflowstatistics",
            index=models.Index(fields=["space_id", "create_time"], name="statistics__space_i_59d3c7_idx"),
        ),
        migrations.AddIndex(
            model_name="taskflowstatistics",
            index=models.Index(fields=["template_id", "create_time"], name="statistics__templat_b16c20_idx"),
        ),
        migrations.AddIndex(
            model_name="taskflowstatistics",
            index=models.Index(fields=["engine_id", "create_time"], name="statistics__engine__cfa157_idx"),
        ),
        migrations.AddIndex(
            model_name="taskflowexecutednodestatistics",
            index=models.Index(
                fields=["space_id", "component_code", "started_time"], name="statistics__space_i_c5e5cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskflowexecutednodestatistics",
            index=models.Index(fields=["task_id", "node_id"], name="statistics__task_id_32368c_idx"),
        ),
        migrations.AddIndex(
            model_name="taskflowexecutednodestatistics",
            index=models.Index(
                fields=["component_code", "status", "started_time"], name="statistics__compone_3df671_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskflowexecutednodestatistics",
            index=models.Index(fields=["engine_id", "started_time"], name="statistics__engine__cd5921_idx"),
        ),
        migrations.AddIndex(
            model_name="pluginexecutionsummary",
            index=models.Index(
                fields=["space_id", "component_code", "period_start"], name="statistics__space_i_4d00e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pluginexecutionsummary",
            unique_together={("period_type", "period_start", "space_id", "component_code", "version")},
        ),
        migrations.AddIndex(
            model_name="dailystatisticssummary",
            index=models.Index(fields=["space_id", "date"], name="statistics__space_i_f7e559_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailystatisticssummary",
            unique_together={("date", "space_id", "scope_type", "scope_value")},
        ),
    ]
