# Generated by Django 3.2.25 on 2026-03-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pluginexecutionsummary",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="taskflowexecutednodestatistics",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="templatenodestatistics",
            name="is_remote",
        ),
        migrations.AddField(
            model_name="pluginexecutionsummary",
            name="component_name",
            field=models.CharField(default="", max_length=255, verbose_name="组件名称"),
        ),
        migrations.AddField(
            model_name="pluginexecutionsummary",
            name="plugin_type",
            field=models.CharField(
                choices=[("component", "内置插件"), ("remote_plugin", "第三方插件"), ("uniform_api", "API插件")],
                db_index=True,
                default="component",
                max_length=32,
                verbose_name="插件类型",
            ),
        ),
        migrations.AddField(
            model_name="taskflowexecutednodestatistics",
            name="component_name",
            field=models.CharField(default="", max_length=255, verbose_name="组件名称"),
        ),
        migrations.AddField(
            model_name="taskflowexecutednodestatistics",
            name="plugin_type",
            field=models.CharField(
                choices=[("component", "内置插件"), ("remote_plugin", "第三方插件"), ("uniform_api", "API插件")],
                db_index=True,
                default="component",
                max_length=32,
                verbose_name="插件类型",
            ),
        ),
        migrations.AddField(
            model_name="templatenodestatistics",
            name="component_name",
            field=models.CharField(default="", max_length=255, verbose_name="组件名称"),
        ),
        migrations.AddField(
            model_name="templatenodestatistics",
            name="plugin_type",
            field=models.CharField(
                choices=[("component", "内置插件"), ("remote_plugin", "第三方插件"), ("uniform_api", "API插件")],
                db_index=True,
                default="component",
                max_length=32,
                verbose_name="插件类型",
            ),
        ),
    ]
