# Generated by Django 3.2.25 on 2026-09-01 15:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HarnessRun",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="运行ID"
                    ),
                ),
                ("platform_key", models.CharField(max_length=64, verbose_name="平台标识")),
                ("platform_app", models.CharField(max_length=32, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=32, verbose_name="操作者")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间ID")),
                ("scope_type", models.CharField(blank=True, max_length=64, null=True, verbose_name="Scope 类型")),
                ("scope_value", models.CharField(blank=True, max_length=128, null=True, verbose_name="Scope 值")),
                ("target_environment", models.CharField(max_length=32, verbose_name="目标环境")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTENT_CAPTURED", "已捕获意图"),
                            ("PLANNING", "规划中"),
                            ("VALIDATING", "校验中"),
                            ("NEEDS_REPAIR", "待修复"),
                            ("DRAFT_READY", "草稿就绪"),
                            ("DEBUGGING", "调试中"),
                            ("RELEASE_READY", "待发布"),
                            ("APPROVAL_PENDING", "审批中"),
                            ("PUBLISHING", "发布中"),
                            ("PUBLISHED", "已发布"),
                            ("EXECUTING", "执行中"),
                            ("SUCCEEDED", "执行成功"),
                            ("FAILED", "执行失败"),
                            ("CANCELLED", "已取消"),
                            ("EVIDENCE_FINALIZED", "证据已固化"),
                        ],
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("mcp_contract_version", models.CharField(max_length=32, verbose_name="MCP 契约版本")),
                ("client_context", models.JSONField(default=dict, verbose_name="客户端上下文")),
                ("artifact_refs", models.JSONField(default=dict, verbose_name="工件引用")),
            ],
            options={
                "verbose_name": "Harness 运行",
                "verbose_name_plural": "Harness 运行",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowPlanRevision",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="修订ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="修订序号")),
                ("intent_spec", models.JSONField(default=dict, verbose_name="意图快照")),
                ("canonical_a2flow", models.JSONField(default=dict, verbose_name="规范化 a2flow")),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_revisions",
                        to="harness.workflowplanrevision",
                        verbose_name="父修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="harness.harnessrun",
                        verbose_name="所属运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "流程计划修订",
                "verbose_name_plural": "流程计划修订",
                "ordering": ["run", "sequence"],
                "unique_together": {("run", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="ValidationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[("validate_workflow", "流程校验"), ("create_workflow_draft", "草稿创建")],
                        max_length=64,
                        verbose_name="校验检查点",
                    ),
                ),
                ("validator_version", models.CharField(max_length=64, verbose_name="校验器版本")),
                (
                    "result",
                    models.CharField(choices=[("PASSED", "通过"), ("FAILED", "失败")], max_length=16, verbose_name="校验结果"),
                ),
                ("risk_manifest", models.JSONField(default=dict, verbose_name="风险清单")),
                ("errors", models.JSONField(default=list, verbose_name="错误")),
                ("warnings", models.JSONField(default=list, verbose_name="警告")),
                ("correlation_id", models.CharField(max_length=64, verbose_name="关联ID")),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.workflowplanrevision",
                        verbose_name="所属修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.harnessrun",
                        verbose_name="所属运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "校验报告",
                "verbose_name_plural": "校验报告",
                "ordering": ["-create_at"],
            },
        ),
        migrations.CreateModel(
            name="HarnessIdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("platform_app", models.CharField(max_length=32, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=32, verbose_name="操作者")),
                ("space_id", models.IntegerField(verbose_name="空间ID")),
                ("tool_name", models.CharField(max_length=64, verbose_name="Tool 名称")),
                ("run_scope", models.CharField(max_length=80, verbose_name="运行作用域")),
                ("idempotency_key", models.CharField(max_length=128, verbose_name="幂等键")),
                ("request_hash", models.CharField(max_length=64, verbose_name="请求哈希")),
                ("response_snapshot", models.JSONField(default=dict, verbose_name="响应快照")),
                ("resource_ref", models.JSONField(default=dict, verbose_name="资源引用")),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="harness.harnessrun",
                        verbose_name="所属运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 幂等记录",
                "verbose_name_plural": "Harness 幂等记录",
                "ordering": ["-create_at"],
                "unique_together": {("platform_app", "actor", "space_id", "tool_name", "run_scope", "idempotency_key")},
            },
        ),
        migrations.CreateModel(
            name="CapabilityBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("node_id", models.CharField(max_length=64, verbose_name="节点ID")),
                ("capability_ref", models.CharField(max_length=255, verbose_name="能力引用")),
                ("resolved_version", models.CharField(max_length=64, verbose_name="精确版本")),
                ("schema_hash", models.CharField(max_length=64, verbose_name="Schema 哈希")),
                ("credential_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="凭证引用")),
                ("risk_level", models.CharField(max_length=16, verbose_name="风险等级")),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bindings",
                        to="harness.workflowplanrevision",
                        verbose_name="所属修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "能力绑定",
                "verbose_name_plural": "能力绑定",
                "ordering": ["id"],
                "unique_together": {("revision", "node_id")},
            },
        ),
    ]
