# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making
蓝鲸流程引擎服务 (BlueKing Flow Engine Service) available.
Copyright (C) 2024 THL A29 Limited,
a Tencent company. All rights reserved.
Licensed under the MIT License (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
either express or implied. See the License for the
specific language governing permissions and limitations under the License.

We undertake not to change the open source license (MIT license) applicable

to the current version of the project delivered to anyone in the future.
"""
# Generated by Django 3.2.25 on 2026-09-03 03:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HarnessRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="运行 ID")),
                ("platform", models.CharField(max_length=64, verbose_name="平台标识")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("environment", models.CharField(max_length=64, verbose_name="目标环境")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTENT_CAPTURED", "Intent captured"),
                            ("PLANNING", "Planning"),
                            ("VALIDATING", "Validating"),
                            ("NEEDS_REPAIR", "Needs repair"),
                            ("DRAFT_READY", "Draft ready"),
                        ],
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("mcp_contract_version", models.CharField(max_length=64, verbose_name="MCP 契约版本")),
                ("client_context", models.JSONField(default=dict, verbose_name="客户端上下文")),
                ("artifact_references", models.JSONField(default=list, verbose_name="工件引用")),
            ],
            options={
                "verbose_name": "Harness 运行",
                "verbose_name_plural": "Harness 运行",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowPlanRevision",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="修订 ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="修订序号")),
                ("intent_spec", models.JSONField(default=dict, verbose_name="意图规格")),
                ("canonical_a2flow", models.JSONField(default=dict, verbose_name="规范化 a2flow")),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_revisions",
                        to="harness.workflowplanrevision",
                        verbose_name="父修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流计划修订",
                "verbose_name_plural": "工作流计划修订",
                "ordering": ["run_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="ValidationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[
                            ("VALIDATE", "Validate"),
                            ("DRAFT", "Draft"),
                            ("DEBUG", "Debug"),
                            ("RELEASE", "Release"),
                            ("EXECUTE", "Execute"),
                        ],
                        max_length=16,
                        verbose_name="检查点",
                    ),
                ),
                ("validator_version", models.CharField(max_length=64, verbose_name="校验器版本")),
                ("result", models.JSONField(default=dict, verbose_name="校验结果")),
                ("risk_manifest", models.JSONField(default=dict, verbose_name="风险清单")),
                ("errors", models.JSONField(default=list, verbose_name="错误")),
                ("warnings", models.JSONField(default=list, verbose_name="告警")),
                ("correlation_id", models.CharField(max_length=128, verbose_name="关联 ID")),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "校验报告",
                "verbose_name_plural": "校验报告",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HarnessIdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(verbose_name="空间 ID")),
                ("tool_name", models.CharField(max_length=128, verbose_name="Tool 名称")),
                ("run_scope", models.CharField(max_length=255, verbose_name="运行作用域")),
                ("idempotency_key", models.CharField(max_length=255, verbose_name="幂等键")),
                ("request_hash", models.CharField(max_length=64, verbose_name="请求哈希")),
                ("response_snapshot", models.JSONField(default=dict, verbose_name="响应快照")),
                ("resource_reference", models.CharField(blank=True, max_length=255, null=True, verbose_name="资源引用")),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 幂等记录",
                "verbose_name_plural": "Harness 幂等记录",
            },
        ),
        migrations.CreateModel(
            name="CapabilityBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("node_id", models.CharField(max_length=128, verbose_name="节点 ID")),
                ("capability_ref", models.TextField(verbose_name="能力引用")),
                ("resolved_version", models.CharField(max_length=128, verbose_name="解析版本")),
                ("schema_hash", models.CharField(max_length=64, verbose_name="Schema 哈希")),
                ("credential_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="凭证引用")),
                (
                    "risk",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_bindings",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "能力绑定",
                "verbose_name_plural": "能力绑定",
            },
        ),
        migrations.AddConstraint(
            model_name="workflowplanrevision",
            constraint=models.UniqueConstraint(fields=("run", "sequence"), name="uniq_harness_run_revision_sequence"),
        ),
        migrations.AddConstraint(
            model_name="harnessidempotencyrecord",
            constraint=models.UniqueConstraint(
                fields=("platform_app", "actor", "space_id", "tool_name", "run_scope", "idempotency_key"),
                name="uniq_harness_idempotency_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="capabilitybinding",
            constraint=models.UniqueConstraint(fields=("revision", "node_id"), name="uniq_harness_revision_node"),
        ),
    ]
