# Generated by Django 3.2.25 on 2026-09-28 08:56

import uuid

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models

import bkflow.harness.models


class Migration(migrations.Migration):

    replaces = [
        ("harness", "0001_initial"),
        ("harness", "0002_harnessidempotencyrecord_status"),
        ("harness", "0003_capabilitybinding_conversion_fingerprint"),
        ("harness", "0004_p1_knowledge_router"),
        ("harness", "0005_p2_debug_token_broker"),
        ("harness", "0006_p3_release_execution"),
        ("harness", "0007_p4_feedback_evalops"),
        ("harness", "0008_idempotency_scope_hash"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HarnessRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="运行 ID")),
                ("platform", models.CharField(max_length=64, verbose_name="平台标识")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("environment", models.CharField(max_length=64, verbose_name="目标环境")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INTENT_CAPTURED", "Intent captured"),
                            ("PLANNING", "Planning"),
                            ("VALIDATING", "Validating"),
                            ("NEEDS_REPAIR", "Needs repair"),
                            ("DRAFT_READY", "Draft ready"),
                        ],
                        max_length=32,
                        verbose_name="状态",
                    ),
                ),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("mcp_contract_version", models.CharField(max_length=64, verbose_name="MCP 契约版本")),
                ("client_context", models.JSONField(default=dict, verbose_name="客户端上下文")),
                ("artifact_references", models.JSONField(default=list, verbose_name="工件引用")),
            ],
            options={
                "verbose_name": "Harness 运行",
                "verbose_name_plural": "Harness 运行",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowPlanRevision",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="修订 ID"
                    ),
                ),
                ("sequence", models.PositiveIntegerField(verbose_name="修订序号")),
                ("intent_spec", models.JSONField(default=dict, verbose_name="意图规格")),
                ("canonical_a2flow", models.JSONField(default=dict, verbose_name="规范化 a2flow")),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                (
                    "parent_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_revisions",
                        to="harness.workflowplanrevision",
                        verbose_name="父修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流计划修订",
                "verbose_name_plural": "工作流计划修订",
                "ordering": ["run_id", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="ValidationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "checkpoint",
                    models.CharField(
                        choices=[
                            ("VALIDATE", "Validate"),
                            ("DRAFT", "Draft"),
                            ("DEBUG", "Debug"),
                            ("RELEASE", "Release"),
                            ("EXECUTE", "Execute"),
                        ],
                        max_length=16,
                        verbose_name="检查点",
                    ),
                ),
                ("validator_version", models.CharField(max_length=64, verbose_name="校验器版本")),
                ("result", models.JSONField(default=dict, verbose_name="校验结果")),
                ("risk_manifest", models.JSONField(default=dict, verbose_name="风险清单")),
                ("errors", models.JSONField(default=list, verbose_name="错误")),
                ("warnings", models.JSONField(default=list, verbose_name="告警")),
                ("correlation_id", models.CharField(max_length=128, verbose_name="关联 ID")),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation_reports",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "校验报告",
                "verbose_name_plural": "校验报告",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HarnessIdempotencyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(verbose_name="空间 ID")),
                ("tool_name", models.CharField(max_length=128, verbose_name="Tool 名称")),
                ("run_scope", models.CharField(max_length=255, verbose_name="运行作用域")),
                ("idempotency_key", models.CharField(max_length=255, verbose_name="幂等键")),
                ("request_hash", models.CharField(max_length=64, verbose_name="请求哈希")),
                ("response_snapshot", models.JSONField(default=dict, verbose_name="响应快照")),
                ("resource_reference", models.CharField(blank=True, max_length=255, null=True, verbose_name="资源引用")),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="idempotency_records",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 幂等记录",
                "verbose_name_plural": "Harness 幂等记录",
            },
        ),
        migrations.CreateModel(
            name="CapabilityBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("node_id", models.CharField(max_length=128, verbose_name="节点 ID")),
                ("capability_ref", models.TextField(verbose_name="能力引用")),
                ("resolved_version", models.CharField(max_length=128, verbose_name="解析版本")),
                ("schema_hash", models.CharField(max_length=64, verbose_name="Schema 哈希")),
                ("credential_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="凭证引用")),
                (
                    "risk",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capability_bindings",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "能力绑定",
                "verbose_name_plural": "能力绑定",
            },
        ),
        migrations.AddConstraint(
            model_name="workflowplanrevision",
            constraint=models.UniqueConstraint(fields=("run", "sequence"), name="uniq_harness_run_revision_sequence"),
        ),
        migrations.AddConstraint(
            model_name="capabilitybinding",
            constraint=models.UniqueConstraint(fields=("revision", "node_id"), name="uniq_harness_revision_node"),
        ),
        migrations.AddField(
            model_name="harnessidempotencyrecord",
            name="status",
            field=models.CharField(
                choices=[("IN_FLIGHT", "In flight"), ("COMPLETED", "Completed"), ("FAILED", "Failed")],
                default="IN_FLIGHT",
                max_length=16,
                verbose_name="幂等状态",
            ),
        ),
        migrations.AddField(
            model_name="capabilitybinding",
            name="conversion_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="转换事实哈希"),
        ),
        migrations.CreateModel(
            name="KnowledgeRetrievalAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("trusted_context_snapshot", models.JSONField(default=dict, verbose_name="可信上下文快照")),
                ("query_fingerprint", models.CharField(max_length=64, verbose_name="查询指纹")),
                ("redacted_query", models.TextField(verbose_name="脱敏查询")),
                ("eligible_binding_ids", models.JSONField(blank=True, default=list, verbose_name="候选绑定 ID")),
                ("provider_call_summaries", models.JSONField(blank=True, default=list, verbose_name="提供方调用摘要")),
                ("hit_refs", models.JSONField(blank=True, default=list, verbose_name="命中引用")),
                ("snapshot_refs", models.JSONField(blank=True, default=list, verbose_name="快照引用")),
                ("correlation_id", models.CharField(db_index=True, max_length=128, verbose_name="关联 ID")),
                ("duration_ms", models.PositiveIntegerField(verbose_name="耗时（毫秒）")),
                ("outcome", models.CharField(max_length=32, verbose_name="检索结果")),
            ],
            options={
                "verbose_name": "知识检索审计",
                "verbose_name_plural": "知识检索审计",
                "ordering": ["-id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSourceBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("provider", models.CharField(max_length=64, verbose_name="知识提供方")),
                ("source_ref", models.TextField(verbose_name="知识源引用")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        verbose_name="知识层级",
                    ),
                ),
                ("platform_key", models.CharField(blank=True, max_length=64, null=True, verbose_name="平台标识")),
                ("space_id", models.IntegerField(blank=True, null=True, verbose_name="空间 ID")),
                ("scope_type", models.CharField(blank=True, max_length=64, null=True, verbose_name="范围类型")),
                ("scope_value", models.CharField(blank=True, max_length=255, null=True, verbose_name="范围值")),
                (
                    "trust_level",
                    models.CharField(
                        choices=[("UNVERIFIED", "Unverified"), ("VERIFIED", "Verified"), ("TRUSTED", "Trusted")],
                        max_length=16,
                        verbose_name="可信等级",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("allowed_apps", models.JSONField(blank=True, default=list, verbose_name="允许应用")),
                ("allowed_actors", models.JSONField(blank=True, default=list, verbose_name="允许操作人")),
                ("data_classification", models.CharField(max_length=64, verbose_name="数据分类")),
                ("snapshot_version", models.CharField(max_length=128, verbose_name="快照版本")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("last_verified_at", models.DateTimeField(blank=True, null=True, verbose_name="最近验证时间")),
                ("owner", models.CharField(max_length=128, verbose_name="负责人")),
                ("reviewer", models.CharField(blank=True, max_length=128, null=True, verbose_name="审核人")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DEPRECATED", "Deprecated"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DISABLED",
                        max_length=16,
                        verbose_name="生命周期状态",
                    ),
                ),
                (
                    "retrieval_mode",
                    models.CharField(
                        choices=[("KEYWORD", "Keyword"), ("VECTOR", "Vector"), ("HYBRID", "Hybrid")],
                        max_length=16,
                        verbose_name="检索模式",
                    ),
                ),
                (
                    "max_top_k",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="最大返回数",
                    ),
                ),
                ("redaction_policy", models.JSONField(blank=True, default=dict, verbose_name="脱敏策略")),
                ("credential_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="凭证引用")),
                ("provider_config", models.JSONField(blank=True, default=dict, verbose_name="提供方非秘密配置")),
                (
                    "active_identity",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name="生效绑定身份"
                    ),
                ),
            ],
            options={
                "verbose_name": "知识源绑定",
                "verbose_name_plural": "知识源绑定",
                "ordering": ["-priority", "id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("platform_key__isnull", True),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", True),
                        ("tier__in", ["GLOBAL", "PUBLIC"]),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", True),
                        ("tier", "PLATFORM"),
                        models.Q(("platform_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", False),
                        ("tier", "SPACE"),
                        models.Q(("platform_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", False),
                        ("scope_value__isnull", False),
                        ("space_id__isnull", False),
                        ("tier", "SCOPE"),
                        models.Q(("platform_key", ""), _negated=True),
                        models.Q(("scope_type", ""), _negated=True),
                        models.Q(("scope_value", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="harness_knowledge_binding_tier_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("active_identity__isnull", False), ("status", "ACTIVE")),
                    models.Q(models.Q(("status", "ACTIVE"), _negated=True), ("active_identity__isnull", True)),
                    _connector="OR",
                ),
                name="harness_knowledge_binding_active_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(("max_top_k__gte", 1), ("max_top_k__lte", 20)),
                name="harness_knowledge_binding_max_top_k",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrievalaudit",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="knowledge_retrieval_audits",
                to="harness.harnessrun",
                verbose_name="Harness 运行",
            ),
        ),
        migrations.CreateModel(
            name="DebugSession",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="调试会话 ID"
                    ),
                ),
                ("template_id", models.PositiveBigIntegerField(db_index=True, verbose_name="模板 ID")),
                ("debug_context_id", models.PositiveBigIntegerField(verbose_name="调试上下文 ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("step", "Step"), ("global", "Global")], max_length=16, verbose_name="调试模式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TERMINATED", "Terminated"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=16,
                        verbose_name="会话状态",
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("tree_fingerprint", models.JSONField(default=dict, verbose_name="流程树指纹")),
                (
                    "active_template_key",
                    models.CharField(
                        blank=True, editable=False, max_length=128, null=True, unique=True, verbose_name="活跃模板键"
                    ),
                ),
                ("current_task_id", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="当前任务 ID")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("trusted_context_snapshot", models.JSONField(default=dict, verbose_name="可信上下文快照")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True, verbose_name="最近心跳时间")),
                ("terminal_reason", models.CharField(blank=True, max_length=512, null=True, verbose_name="终态原因")),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debug_sessions",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 调试会话",
                "verbose_name_plural": "Harness 调试会话",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="harnessrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("INTENT_CAPTURED", "Intent captured"),
                    ("PLANNING", "Planning"),
                    ("VALIDATING", "Validating"),
                    ("NEEDS_REPAIR", "Needs repair"),
                    ("DRAFT_READY", "Draft ready"),
                    ("DEBUGGING", "Debugging"),
                    ("RELEASE_READY", "Release ready"),
                ],
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.CreateModel(
            name="TokenLease",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Token 租约 ID",
                    ),
                ),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("TEMPLATE", "Template"), ("SCOPE", "Scope")], max_length=32, verbose_name="资源类型"
                    ),
                ),
                ("resource_id", models.CharField(max_length=128, verbose_name="资源 ID")),
                ("permission", models.CharField(choices=[("MOCK", "Mock")], max_length=32, verbose_name="权限")),
                ("issuer_ref", models.CharField(max_length=255, verbose_name="颁发方引用")),
                ("token_fingerprint", models.CharField(max_length=64, verbose_name="Token 指纹")),
                ("issued_at", models.DateTimeField(verbose_name="颁发时间")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="撤销时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked"), ("EXPIRED", "Expired")],
                        max_length=16,
                        verbose_name="租约状态",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="token_leases",
                        to="harness.debugsession",
                        verbose_name="调试会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness Token 租约",
                "verbose_name_plural": "Harness Token 租约",
                "ordering": ["-issued_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EvidenceEvent",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="证据事件 ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64, verbose_name="事件类型")),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                ("redacted_payload", models.JSONField(default=dict, verbose_name="脱敏载荷")),
                ("artifact_refs", models.JSONField(blank=True, default=list, verbose_name="工件引用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("correlation_id", models.CharField(db_index=True, max_length=128, verbose_name="关联 ID")),
                (
                    "redaction_version",
                    models.CharField(default="builtin-credential-v1", max_length=64, verbose_name="脱敏版本"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="发生时间"),
                ),
                (
                    "debug_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.debugsession",
                        verbose_name="调试会话",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.harnessrun",
                        verbose_name="Harness 运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 证据事件",
                "verbose_name_plural": "Harness 证据事件",
                "ordering": ["occurred_at", "id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="debugsession",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debug_sessions",
                to="harness.harnessrun",
                verbose_name="Harness 运行",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("revoked_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("revoked_at__isnull", False), ("status", "REVOKED")),
                    models.Q(("revoked_at__isnull", True), ("status", "EXPIRED")),
                    _connector="OR",
                ),
                name="harness_token_lease_status_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(("expires_at__gt", django.db.models.expressions.F("issued_at"))),
                name="harness_token_lease_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="debugsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("active_template_key__isnull", False), ("status__in", ["ACTIVE", "RUNNING"])),
                    models.Q(
                        ("active_template_key__isnull", True),
                        ("status__in", ["COMPLETED", "FAILED", "TERMINATED", "EXPIRED"]),
                    ),
                    _connector="OR",
                ),
                name="harness_debug_session_active_template_key",
            ),
        ),
        migrations.CreateModel(
            name="ReleaseManifest",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="发布清单 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("draft_template_id", models.PositiveBigIntegerField(verbose_name="草稿模板 ID")),
                ("draft_snapshot_id", models.PositiveBigIntegerField(verbose_name="草稿快照 ID")),
                ("draft_tree_fingerprint", models.JSONField(default=dict, verbose_name="草稿树指纹")),
                ("capability_snapshot", models.JSONField(blank=True, default=list, verbose_name="能力快照")),
                ("validation_evidence_refs", models.JSONField(default=list, verbose_name="校验证据引用")),
                ("debug_evidence_refs", models.JSONField(default=list, verbose_name="调试证据引用")),
                ("postcondition_spec", models.JSONField(default=dict, verbose_name="后置条件")),
                ("risk_manifest", models.JSONField(default=dict, verbose_name="风险清单")),
                ("required_approvals", models.JSONField(blank=True, default=list, verbose_name="审批需求")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                (
                    "manifest_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="清单哈希"
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_manifests",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 发布清单",
                "verbose_name_plural": "Harness 发布清单",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prepare_release", "Prepare release"),
                    ("publish_workflow", "Publish workflow"),
                    ("start_workflow_execution", "Start workflow execution"),
                    ("get_workflow_execution", "Get workflow execution"),
                    ("pause", "Pause"),
                    ("resume", "Resume"),
                    ("revoke", "Revoke"),
                    ("retry", "Retry"),
                    ("skip", "Skip"),
                    ("callback", "Callback"),
                    ("forced_fail", "Forced fail"),
                    ("skip_exg", "Skip exclusive gateway"),
                    ("skip_cpg", "Skip conditional parallel gateway"),
                    ("run_debug_global_real", "Run global real debug"),
                ],
                max_length=64,
                null=True,
                verbose_name="授权动作",
            ),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="action_digest",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="动作哈希"),
        ),
        migrations.AlterField(
            model_name="harnessrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("INTENT_CAPTURED", "Intent captured"),
                    ("PLANNING", "Planning"),
                    ("VALIDATING", "Validating"),
                    ("NEEDS_REPAIR", "Needs repair"),
                    ("DRAFT_READY", "Draft ready"),
                    ("DEBUGGING", "Debugging"),
                    ("RELEASE_READY", "Release ready"),
                    ("APPROVAL_PENDING", "Approval pending"),
                    ("PUBLISHING", "Publishing"),
                    ("PUBLISHED", "Published"),
                    ("EXECUTING", "Executing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("EVIDENCE_FINALIZED", "Evidence finalized"),
                ],
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="permission",
            field=models.CharField(
                choices=[("MOCK", "Mock"), ("VIEW", "View"), ("EDIT", "Edit"), ("OPERATE", "Operate")],
                max_length=32,
                verbose_name="权限",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="resource_type",
            field=models.CharField(
                choices=[("TEMPLATE", "Template"), ("SCOPE", "Scope"), ("TASK", "Task")],
                max_length=32,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_leases",
                to="harness.debugsession",
                verbose_name="调试会话",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                    ("PREPARE_RELEASE", "Prepare release"),
                    ("PUBLISH", "Publish"),
                    ("PRE_EXECUTE", "Pre execute"),
                    ("POSTCONDITION", "Postcondition"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.CreateModel(
            name="ReleasePublication",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="发布结果 ID"
                    ),
                ),
                ("published_template_id", models.PositiveBigIntegerField(verbose_name="已发布模板 ID")),
                ("published_snapshot_id", models.PositiveBigIntegerField(verbose_name="已发布快照 ID")),
                ("published_version", models.CharField(max_length=32, verbose_name="已发布版本")),
                ("operator", models.CharField(blank=True, max_length=128, verbose_name="发布人")),
                ("publish_idempotency_ref", models.CharField(max_length=255, verbose_name="发布幂等引用")),
                (
                    "publication_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="发布结果哈希"
                    ),
                ),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="发布时间")),
                (
                    "manifest",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="harness.releasemanifest",
                        verbose_name="发布清单",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 发布结果",
                "verbose_name_plural": "Harness 发布结果",
                "ordering": ["-published_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="releasemanifest",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_manifests",
                to="harness.harnessrun",
                verbose_name="运行",
            ),
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="执行 ID"
                    ),
                ),
                ("published_template_id", models.PositiveBigIntegerField(verbose_name="已发布模板 ID")),
                ("published_snapshot_id", models.PositiveBigIntegerField(verbose_name="已发布快照 ID")),
                ("published_version", models.CharField(max_length=32, verbose_name="已发布版本")),
                ("task_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="任务引用")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CREATE_DISPATCHING", "Create dispatching"),
                            ("CREATE_UNCERTAIN", "Create uncertain"),
                            ("CREATED", "Created"),
                            ("START_DISPATCHING", "Start dispatching"),
                            ("START_UNCERTAIN", "Start uncertain"),
                            ("EXECUTING", "Executing"),
                            ("PAUSED", "Paused"),
                            ("CONTROL_DISPATCHING", "Control dispatching"),
                            ("CONTROL_UNCERTAIN", "Control uncertain"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="执行状态",
                    ),
                ),
                ("start_idempotency_key", models.CharField(max_length=128, verbose_name="启动幂等键")),
                (
                    "create_idempotency_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="创建幂等引用"),
                ),
                (
                    "start_idempotency_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="启动幂等引用"),
                ),
                ("control_idempotency_refs", models.JSONField(blank=True, default=list, verbose_name="控制幂等引用")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "postcondition_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="后置条件状态",
                    ),
                ),
                ("postcondition_report", models.JSONField(blank=True, default=dict, verbose_name="后置条件报告")),
                ("last_engine_state", models.CharField(blank=True, max_length=64, null=True, verbose_name="最近引擎状态")),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True, verbose_name="最近心跳")),
                ("terminal_at", models.DateTimeField(blank=True, null=True, verbose_name="终态时间")),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="harness.releasemanifest",
                        verbose_name="发布清单",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 执行",
                "verbose_name_plural": "Harness 执行",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="证据包 ID"
                    ),
                ),
                ("evidence_event_refs", models.JSONField(default=list, verbose_name="证据事件引用")),
                ("artifact_refs", models.JSONField(blank=True, default=list, verbose_name="工件引用")),
                ("redaction_version", models.CharField(max_length=64, verbose_name="脱敏版本")),
                (
                    "bundle_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="证据包哈希"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")],
                        max_length=16,
                        verbose_name="结果",
                    ),
                ),
                ("finalized_at", models.DateTimeField(verbose_name="完成时间")),
                (
                    "retention_class",
                    models.CharField(
                        choices=[("STANDARD", "Standard")], default="STANDARD", max_length=16, verbose_name="保留级别"
                    ),
                ),
                (
                    "execution",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundle",
                        to="harness.executionrun",
                        verbose_name="执行",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundles",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_bundles",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 证据包",
                "verbose_name_plural": "Harness 证据包",
                "ordering": ["-finalized_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="审批请求 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("prepare_release", "Prepare release"),
                            ("publish_workflow", "Publish workflow"),
                            ("start_workflow_execution", "Start workflow execution"),
                            ("get_workflow_execution", "Get workflow execution"),
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("revoke", "Revoke"),
                            ("retry", "Retry"),
                            ("skip", "Skip"),
                            ("callback", "Callback"),
                            ("forced_fail", "Forced fail"),
                            ("skip_exg", "Skip exclusive gateway"),
                            ("skip_cpg", "Skip conditional parallel gateway"),
                            ("run_debug_global_real", "Run global real debug"),
                        ],
                        max_length=64,
                        verbose_name="审批动作",
                    ),
                ),
                ("action_digest", models.CharField(max_length=64, verbose_name="动作哈希")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("approver", models.CharField(blank=True, max_length=128, null=True, verbose_name="审批人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_summary", models.JSONField(default=dict, verbose_name="风险摘要")),
                ("receipt_provider", models.CharField(blank=True, max_length=64, null=True, verbose_name="回执提供方")),
                ("receipt_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="回执引用")),
                ("receipt_digest", models.CharField(blank=True, max_length=64, null=True, verbose_name="回执哈希")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="申请时间")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="验证时间")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("verifier_version", models.CharField(blank=True, max_length=64, null=True, verbose_name="验证器版本")),
                (
                    "active_approval_key",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name="活跃审批键"
                    ),
                ),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="harness.releasemanifest",
                        verbose_name="发布清单",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_requests",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 审批请求",
                "verbose_name_plural": "Harness 审批请求",
                "ordering": ["-requested_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="evidenceevent",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_events",
                to="harness.executionrun",
                verbose_name="流程执行",
            ),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_leases",
                to="harness.executionrun",
                verbose_name="流程执行",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                check=models.Q(("debug_session__isnull", True), ("execution__isnull", True), _connector="OR"),
                name="harness_evidence_at_most_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("action__isnull", True),
                        ("action_digest__isnull", True),
                        ("execution__isnull", True),
                        ("session__isnull", False),
                    ),
                    models.Q(
                        ("action__isnull", False),
                        ("action_digest__isnull", False),
                        ("execution__isnull", False),
                        ("session__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="harness_token_lease_exact_owner_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.UniqueConstraint(
                fields=("manifest", "start_idempotency_key"), name="uniq_harness_manifest_start_key"
            ),
        ),
        migrations.CreateModel(
            name="GenerationFeedback",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="生成反馈 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="反馈人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CORRECTION", "Correction"),
                            ("RUNTIME_ISSUE", "Runtime issue"),
                            ("BUSINESS_OUTCOME", "Business outcome"),
                        ],
                        max_length=32,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                ("redacted_summary", models.TextField(verbose_name="脱敏摘要")),
                (
                    "correction_artifact_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="纠正工件引用"),
                ),
                ("observed_outcome", models.JSONField(blank=True, default=dict, verbose_name="观测结果")),
                ("consent_scope", models.CharField(max_length=64, verbose_name="授权用途")),
                ("idempotency_digest", models.CharField(max_length=64, verbose_name="幂等摘要")),
                (
                    "redaction_version",
                    models.CharField(default="builtin-credential-v1", max_length=64, verbose_name="脱敏版本"),
                ),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_feedback",
                        to="harness.evidencebundle",
                        verbose_name="证据包",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_feedback",
                        to="harness.executionrun",
                        verbose_name="流程执行",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 生成反馈",
                "verbose_name_plural": "Harness 生成反馈",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ImprovementCandidate",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="改进候选 ID"
                    ),
                ),
                (
                    "candidate_type",
                    models.CharField(
                        choices=[
                            ("KNOWLEDGE", "Knowledge"),
                            ("REGISTRY", "Registry"),
                            ("VALIDATOR_POLICY", "Validator policy"),
                            ("PROMPT_SKILL", "Prompt or skill"),
                            ("EVAL", "Evaluation"),
                        ],
                        max_length=32,
                        verbose_name="候选类型",
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        choices=[
                            ("REQUIREMENT", "Requirement"),
                            ("KNOWLEDGE", "Knowledge"),
                            ("PROMPT", "Prompt"),
                            ("SCHEMA", "Schema"),
                            ("RESOLVER", "Resolver"),
                            ("VALIDATOR", "Validator"),
                            ("PERMISSION", "Permission"),
                            ("PLUGIN", "Plugin"),
                            ("ENVIRONMENT", "Environment"),
                            ("POSTCONDITION", "Postcondition"),
                        ],
                        max_length=32,
                        verbose_name="归因类型",
                    ),
                ),
                ("proposal_artifact_ref", models.CharField(max_length=255, verbose_name="脱敏提案工件")),
                ("owner_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="负责人引用")),
                ("reviewer_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="审核人引用")),
                ("target_system", models.CharField(max_length=128, verbose_name="目标系统")),
                (
                    "target_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="目标知识层级",
                    ),
                ),
                ("target_platform_key", models.CharField(blank=True, max_length=64, null=True, verbose_name="目标平台")),
                ("target_space_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="目标空间 ID")),
                ("target_scope_type", models.CharField(blank=True, max_length=64, null=True, verbose_name="目标范围类型")),
                ("target_scope_value", models.CharField(blank=True, max_length=255, null=True, verbose_name="目标范围值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="候选状态",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="归因置信度",
                    ),
                ),
                ("regression_case_refs", models.JSONField(blank=True, default=list, verbose_name="回归用例引用")),
                ("impact_artifact_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="影响分析工件")),
                ("rollback_artifact_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="回滚工件")),
                ("source_version", models.CharField(max_length=128, verbose_name="来源版本")),
                ("current_version", models.CharField(max_length=128, verbose_name="当前版本")),
                ("target_version", models.CharField(max_length=128, verbose_name="目标版本")),
                (
                    "promotion_receipt_digest",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="晋级回执摘要"),
                ),
                ("revision_number", models.PositiveIntegerField(default=1, verbose_name="候选修订序号")),
                (
                    "parent_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="harness.improvementcandidate",
                        verbose_name="父候选",
                    ),
                ),
                (
                    "source_evidence_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improvement_candidates",
                        to="harness.evidencebundle",
                        verbose_name="来源证据包",
                    ),
                ),
                (
                    "source_feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improvement_candidates",
                        to="harness.generationfeedback",
                        verbose_name="来源反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 改进候选",
                "verbose_name_plural": "Harness 改进候选",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                    ("PREPARE_RELEASE", "Prepare release"),
                    ("PUBLISH", "Publish"),
                    ("PRE_EXECUTE", "Pre execute"),
                    ("POSTCONDITION", "Postcondition"),
                    ("FEEDBACK_INTAKE", "Feedback intake"),
                    ("PROMOTION_EVAL", "Promotion evaluation"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.CreateModel(
            name="HarnessEvalRun",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="评测运行 ID"
                    ),
                ),
                ("base_release_version", models.CharField(max_length=128, verbose_name="基线发布版本")),
                ("candidate_release_version", models.CharField(max_length=128, verbose_name="候选发布版本")),
                (
                    "runner_mode",
                    models.CharField(
                        choices=[("LOCAL_DETERMINISTIC", "Local deterministic"), ("SIGNED_BKAIDEV", "Signed BKAIDev")],
                        max_length=32,
                        verbose_name="Runner 模式",
                    ),
                ),
                ("package_hash", models.CharField(max_length=64, verbose_name="评测包哈希")),
                ("result_hash", models.CharField(blank=True, max_length=64, null=True, verbose_name="评测结果哈希")),
                ("signed_result_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="签名结果引用")),
                ("signed_result_digest", models.CharField(blank=True, max_length=64, null=True, verbose_name="签名结果摘要")),
                ("aggregate_metrics", models.JSONField(blank=True, default=dict, verbose_name="聚合指标")),
                (
                    "safety_result",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PASSED", "Passed"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                        verbose_name="安全结果",
                    ),
                ),
                ("threshold_snapshot", models.JSONField(default=dict, verbose_name="门禁阈值快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="评测状态",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finalized_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eval_runs",
                        to="harness.improvementcandidate",
                        verbose_name="改进候选",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 评测运行",
                "verbose_name_plural": "Harness 评测运行",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="HarnessEvalCase",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="评测用例 ID"
                    ),
                ),
                ("case_id", models.CharField(max_length=128, verbose_name="用例标识")),
                ("case_version", models.CharField(max_length=64, verbose_name="用例版本")),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="适用知识层级",
                    ),
                ),
                ("scope", models.CharField(max_length=255, verbose_name="适用范围")),
                ("sanitized_input_artifact_ref", models.CharField(max_length=255, verbose_name="脱敏输入工件")),
                ("expected_invariants", models.JSONField(default=dict, verbose_name="预期不变量")),
                ("scoring_schema", models.JSONField(default=dict, verbose_name="评分 Schema")),
                ("safety_tags", models.JSONField(blank=True, default=list, verbose_name="安全标签")),
                (
                    "fixture_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="Fixture 哈希"
                    ),
                ),
                (
                    "source_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eval_cases",
                        to="harness.improvementcandidate",
                        verbose_name="来源候选",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 评测用例",
                "verbose_name_plural": "Harness 评测用例",
                "ordering": ["case_id", "case_version"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KnowledgeCandidate",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="knowledge_candidate",
                        serialize=False,
                        to="harness.improvementcandidate",
                        verbose_name="改进候选",
                    ),
                ),
                ("target_source_ref", models.TextField(verbose_name="目标知识源引用")),
                ("proposed_snapshot_lineage", models.JSONField(default=dict, verbose_name="建议快照谱系")),
                ("citation_refs", models.JSONField(blank=True, default=list, verbose_name="引用来源")),
                ("conflict_set", models.JSONField(blank=True, default=list, verbose_name="冲突引用")),
                (
                    "target_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_candidates",
                        to="harness.knowledgesourcebinding",
                        verbose_name="目标知识绑定",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 知识改进候选",
                "verbose_name_plural": "Harness 知识改进候选",
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="harnessevalrun",
            constraint=models.UniqueConstraint(
                fields=("candidate", "runner_mode", "package_hash"), name="uniq_harness_eval_candidate_package"
            ),
        ),
        migrations.AddConstraint(
            model_name="harnessevalcase",
            constraint=models.UniqueConstraint(
                fields=("case_id", "case_version"), name="uniq_harness_eval_case_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationfeedback",
            constraint=models.UniqueConstraint(
                fields=("platform_app", "actor", "space_id", "run", "idempotency_digest"),
                name="uniq_harness_feedback_identity_digest",
            ),
        ),
        migrations.AddField(
            model_name="harnessidempotencyrecord",
            name="scope_hash",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True, verbose_name="幂等作用域摘要"),
        ),
    ]
