# Generated by Django 3.2.25 on 2026-09-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="harnessidempotencyrecord",
            name="status",
            field=models.CharField(
                choices=[("IN_FLIGHT", "进行中"), ("COMPLETED", "已完成"), ("FAILED", "失败")],
                default="IN_FLIGHT",
                max_length=16,
                verbose_name="幂等状态",
            ),
        ),
    ]
