# Generated by Django 3.2.25 on 2026-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0002_harnessidempotencyrecord_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="capabilitybinding",
            name="conversion_fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="转换事实哈希"),
        ),
    ]
