# Generated by Django 3.2.25 on 2026-09-04 03:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0003_capabilitybinding_conversion_fingerprint"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeRetrievalAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("trusted_context_snapshot", models.JSONField(default=dict, verbose_name="可信上下文快照")),
                ("query_fingerprint", models.CharField(max_length=64, verbose_name="查询指纹")),
                ("redacted_query", models.TextField(verbose_name="脱敏查询")),
                ("eligible_binding_ids", models.JSONField(blank=True, default=list, verbose_name="候选绑定 ID")),
                ("provider_call_summaries", models.JSONField(blank=True, default=list, verbose_name="提供方调用摘要")),
                ("hit_refs", models.JSONField(blank=True, default=list, verbose_name="命中引用")),
                ("snapshot_refs", models.JSONField(blank=True, default=list, verbose_name="快照引用")),
                ("correlation_id", models.CharField(db_index=True, max_length=128, verbose_name="关联 ID")),
                ("duration_ms", models.PositiveIntegerField(verbose_name="耗时（毫秒）")),
                ("outcome", models.CharField(max_length=32, verbose_name="检索结果")),
            ],
            options={
                "verbose_name": "知识检索审计",
                "verbose_name_plural": "知识检索审计",
                "ordering": ["-id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeSourceBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                ("provider", models.CharField(max_length=64, verbose_name="知识提供方")),
                ("source_ref", models.TextField(verbose_name="知识源引用")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        verbose_name="知识层级",
                    ),
                ),
                ("platform_key", models.CharField(blank=True, max_length=64, null=True, verbose_name="平台标识")),
                ("space_id", models.IntegerField(blank=True, null=True, verbose_name="空间 ID")),
                ("scope_type", models.CharField(blank=True, max_length=64, null=True, verbose_name="范围类型")),
                ("scope_value", models.CharField(blank=True, max_length=255, null=True, verbose_name="范围值")),
                (
                    "trust_level",
                    models.CharField(
                        choices=[("UNVERIFIED", "Unverified"), ("VERIFIED", "Verified"), ("TRUSTED", "Trusted")],
                        max_length=16,
                        verbose_name="可信等级",
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="优先级")),
                ("environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("allowed_apps", models.JSONField(blank=True, default=list, verbose_name="允许应用")),
                ("allowed_actors", models.JSONField(blank=True, default=list, verbose_name="允许操作人")),
                ("data_classification", models.CharField(max_length=64, verbose_name="数据分类")),
                ("snapshot_version", models.CharField(max_length=128, verbose_name="快照版本")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("last_verified_at", models.DateTimeField(blank=True, null=True, verbose_name="最近验证时间")),
                ("owner", models.CharField(max_length=128, verbose_name="负责人")),
                ("reviewer", models.CharField(blank=True, max_length=128, null=True, verbose_name="审核人")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DISABLED", "Disabled"),
                            ("DEPRECATED", "Deprecated"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DISABLED",
                        max_length=16,
                        verbose_name="生命周期状态",
                    ),
                ),
                (
                    "retrieval_mode",
                    models.CharField(
                        choices=[("KEYWORD", "Keyword"), ("VECTOR", "Vector"), ("HYBRID", "Hybrid")],
                        max_length=16,
                        verbose_name="检索模式",
                    ),
                ),
                (
                    "max_top_k",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="最大返回数",
                    ),
                ),
                ("redaction_policy", models.JSONField(blank=True, default=dict, verbose_name="脱敏策略")),
                ("credential_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="凭证引用")),
                ("provider_config", models.JSONField(blank=True, default=dict, verbose_name="提供方非秘密配置")),
                (
                    "active_identity",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name="生效绑定身份"
                    ),
                ),
            ],
            options={
                "verbose_name": "知识源绑定",
                "verbose_name_plural": "知识源绑定",
                "ordering": ["-priority", "id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("platform_key__isnull", True),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", True),
                        ("tier__in", ["GLOBAL", "PUBLIC"]),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", True),
                        ("tier", "PLATFORM"),
                        models.Q(("platform_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", True),
                        ("scope_value__isnull", True),
                        ("space_id__isnull", False),
                        ("tier", "SPACE"),
                        models.Q(("platform_key", ""), _negated=True),
                    ),
                    models.Q(
                        ("platform_key__isnull", False),
                        ("scope_type__isnull", False),
                        ("scope_value__isnull", False),
                        ("space_id__isnull", False),
                        ("tier", "SCOPE"),
                        models.Q(("platform_key", ""), _negated=True),
                        models.Q(("scope_type", ""), _negated=True),
                        models.Q(("scope_value", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="harness_knowledge_binding_tier_dimensions",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("active_identity__isnull", False), ("status", "ACTIVE")),
                    models.Q(models.Q(("status", "ACTIVE"), _negated=True), ("active_identity__isnull", True)),
                    _connector="OR",
                ),
                name="harness_knowledge_binding_active_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="knowledgesourcebinding",
            constraint=models.CheckConstraint(
                check=models.Q(("max_top_k__gte", 1), ("max_top_k__lte", 20)),
                name="harness_knowledge_binding_max_top_k",
            ),
        ),
        migrations.AddField(
            model_name="knowledgeretrievalaudit",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="knowledge_retrieval_audits",
                to="harness.harnessrun",
                verbose_name="Harness 运行",
            ),
        ),
    ]
