# Generated by Django 3.2.25 on 2026-09-04 09:29

import uuid

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0004_p1_knowledge_router"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugSession",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="调试会话 ID"
                    ),
                ),
                ("template_id", models.PositiveBigIntegerField(db_index=True, verbose_name="模板 ID")),
                ("debug_context_id", models.PositiveBigIntegerField(verbose_name="调试上下文 ID")),
                (
                    "mode",
                    models.CharField(
                        choices=[("step", "Step"), ("global", "Global")], max_length=16, verbose_name="调试模式"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("TERMINATED", "Terminated"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=16,
                        verbose_name="会话状态",
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("tree_fingerprint", models.JSONField(default=dict, verbose_name="流程树指纹")),
                (
                    "active_template_key",
                    models.CharField(
                        blank=True, editable=False, max_length=128, null=True, unique=True, verbose_name="活跃模板键"
                    ),
                ),
                ("current_task_id", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="当前任务 ID")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("trusted_context_snapshot", models.JSONField(default=dict, verbose_name="可信上下文快照")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True, verbose_name="最近心跳时间")),
                ("terminal_reason", models.CharField(blank=True, max_length=512, null=True, verbose_name="终态原因")),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debug_sessions",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 调试会话",
                "verbose_name_plural": "Harness 调试会话",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="harnessrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("INTENT_CAPTURED", "Intent captured"),
                    ("PLANNING", "Planning"),
                    ("VALIDATING", "Validating"),
                    ("NEEDS_REPAIR", "Needs repair"),
                    ("DRAFT_READY", "Draft ready"),
                    ("DEBUGGING", "Debugging"),
                    ("RELEASE_READY", "Release ready"),
                ],
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.CreateModel(
            name="TokenLease",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Token 租约 ID",
                    ),
                ),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("TEMPLATE", "Template"), ("SCOPE", "Scope")], max_length=32, verbose_name="资源类型"
                    ),
                ),
                ("resource_id", models.CharField(max_length=128, verbose_name="资源 ID")),
                ("permission", models.CharField(choices=[("MOCK", "Mock")], max_length=32, verbose_name="权限")),
                ("issuer_ref", models.CharField(max_length=255, verbose_name="颁发方引用")),
                ("token_fingerprint", models.CharField(max_length=64, verbose_name="Token 指纹")),
                ("issued_at", models.DateTimeField(verbose_name="颁发时间")),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="撤销时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("REVOKED", "Revoked"), ("EXPIRED", "Expired")],
                        max_length=16,
                        verbose_name="租约状态",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="token_leases",
                        to="harness.debugsession",
                        verbose_name="调试会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness Token 租约",
                "verbose_name_plural": "Harness Token 租约",
                "ordering": ["-issued_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EvidenceEvent",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="证据事件 ID"
                    ),
                ),
                ("event_type", models.CharField(max_length=64, verbose_name="事件类型")),
                ("action", models.CharField(max_length=64, verbose_name="动作")),
                ("redacted_payload", models.JSONField(default=dict, verbose_name="脱敏载荷")),
                ("artifact_refs", models.JSONField(blank=True, default=list, verbose_name="工件引用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("correlation_id", models.CharField(db_index=True, max_length=128, verbose_name="关联 ID")),
                (
                    "redaction_version",
                    models.CharField(default="builtin-credential-v1", max_length=64, verbose_name="脱敏版本"),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="发生时间"),
                ),
                (
                    "debug_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.debugsession",
                        verbose_name="调试会话",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_events",
                        to="harness.harnessrun",
                        verbose_name="Harness 运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 证据事件",
                "verbose_name_plural": "Harness 证据事件",
                "ordering": ["occurred_at", "id"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="debugsession",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debug_sessions",
                to="harness.harnessrun",
                verbose_name="Harness 运行",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("revoked_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("revoked_at__isnull", False), ("status", "REVOKED")),
                    models.Q(("revoked_at__isnull", True), ("status", "EXPIRED")),
                    _connector="OR",
                ),
                name="harness_token_lease_status_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(("expires_at__gt", django.db.models.expressions.F("issued_at"))),
                name="harness_token_lease_expiry_after_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="debugsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("active_template_key__isnull", False), ("status__in", ["ACTIVE", "RUNNING"])),
                    models.Q(
                        ("active_template_key__isnull", True),
                        ("status__in", ["COMPLETED", "FAILED", "TERMINATED", "EXPIRED"]),
                    ),
                    _connector="OR",
                ),
                name="harness_debug_session_active_template_key",
            ),
        ),
    ]
