# Generated by Django 3.2.25 on 2026-09-04 20:36

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import bkflow.harness.models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0005_p2_debug_token_broker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalRequest",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="审批请求 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("prepare_release", "Prepare release"),
                            ("publish_workflow", "Publish workflow"),
                            ("start_workflow_execution", "Start workflow execution"),
                            ("get_workflow_execution", "Get workflow execution"),
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("revoke", "Revoke"),
                            ("retry", "Retry"),
                            ("skip", "Skip"),
                            ("callback", "Callback"),
                            ("forced_fail", "Forced fail"),
                            ("skip_exg", "Skip exclusive gateway"),
                            ("skip_cpg", "Skip conditional parallel gateway"),
                            ("run_debug_global_real", "Run global real debug"),
                        ],
                        max_length=64,
                        verbose_name="审批动作",
                    ),
                ),
                ("action_digest", models.CharField(max_length=64, verbose_name="动作哈希")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("approver", models.CharField(blank=True, max_length=128, null=True, verbose_name="审批人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                ("risk_summary", models.JSONField(default=dict, verbose_name="风险摘要")),
                ("receipt_provider", models.CharField(blank=True, max_length=64, null=True, verbose_name="回执提供方")),
                ("receipt_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="回执引用")),
                ("receipt_digest", models.CharField(blank=True, max_length=64, null=True, verbose_name="回执哈希")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                ("requested_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="申请时间")),
                ("verified_at", models.DateTimeField(blank=True, null=True, verbose_name="验证时间")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="过期时间")),
                ("verifier_version", models.CharField(blank=True, max_length=64, null=True, verbose_name="验证器版本")),
                (
                    "active_approval_key",
                    models.CharField(
                        blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name="活跃审批键"
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 审批请求",
                "verbose_name_plural": "Harness 审批请求",
                "ordering": ["-requested_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="EvidenceBundle",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="证据包 ID"
                    ),
                ),
                ("evidence_event_refs", models.JSONField(default=list, verbose_name="证据事件引用")),
                ("artifact_refs", models.JSONField(blank=True, default=list, verbose_name="工件引用")),
                ("redaction_version", models.CharField(max_length=64, verbose_name="脱敏版本")),
                (
                    "bundle_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="证据包哈希"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")],
                        max_length=16,
                        verbose_name="结果",
                    ),
                ),
                ("finalized_at", models.DateTimeField(verbose_name="完成时间")),
                (
                    "retention_class",
                    models.CharField(
                        choices=[("STANDARD", "Standard")], default="STANDARD", max_length=16, verbose_name="保留级别"
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 证据包",
                "verbose_name_plural": "Harness 证据包",
                "ordering": ["-finalized_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ExecutionRun",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="执行 ID"
                    ),
                ),
                ("published_template_id", models.PositiveBigIntegerField(verbose_name="已发布模板 ID")),
                ("published_snapshot_id", models.PositiveBigIntegerField(verbose_name="已发布快照 ID")),
                ("published_version", models.CharField(max_length=32, verbose_name="已发布版本")),
                ("task_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="任务引用")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CREATE_DISPATCHING", "Create dispatching"),
                            ("CREATE_UNCERTAIN", "Create uncertain"),
                            ("CREATED", "Created"),
                            ("START_DISPATCHING", "Start dispatching"),
                            ("START_UNCERTAIN", "Start uncertain"),
                            ("EXECUTING", "Executing"),
                            ("PAUSED", "Paused"),
                            ("CONTROL_DISPATCHING", "Control dispatching"),
                            ("CONTROL_UNCERTAIN", "Control uncertain"),
                            ("SUCCEEDED", "Succeeded"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=32,
                        verbose_name="执行状态",
                    ),
                ),
                ("start_idempotency_key", models.CharField(max_length=128, verbose_name="启动幂等键")),
                (
                    "create_idempotency_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="创建幂等引用"),
                ),
                (
                    "start_idempotency_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="启动幂等引用"),
                ),
                ("control_idempotency_refs", models.JSONField(blank=True, default=list, verbose_name="控制幂等引用")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="操作人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "postcondition_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="后置条件状态",
                    ),
                ),
                ("postcondition_report", models.JSONField(blank=True, default=dict, verbose_name="后置条件报告")),
                ("last_engine_state", models.CharField(blank=True, max_length=64, null=True, verbose_name="最近引擎状态")),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True, verbose_name="最近心跳")),
                ("terminal_at", models.DateTimeField(blank=True, null=True, verbose_name="终态时间")),
            ],
            options={
                "verbose_name": "Harness 执行",
                "verbose_name_plural": "Harness 执行",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="ReleaseManifest",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="发布清单 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("draft_template_id", models.PositiveBigIntegerField(verbose_name="草稿模板 ID")),
                ("draft_snapshot_id", models.PositiveBigIntegerField(verbose_name="草稿快照 ID")),
                ("draft_tree_fingerprint", models.JSONField(default=dict, verbose_name="草稿树指纹")),
                ("capability_snapshot", models.JSONField(blank=True, default=list, verbose_name="能力快照")),
                ("validation_evidence_refs", models.JSONField(default=list, verbose_name="校验证据引用")),
                ("debug_evidence_refs", models.JSONField(default=list, verbose_name="调试证据引用")),
                ("postcondition_spec", models.JSONField(default=dict, verbose_name="后置条件")),
                ("risk_manifest", models.JSONField(default=dict, verbose_name="风险清单")),
                ("required_approvals", models.JSONField(blank=True, default=list, verbose_name="审批需求")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                (
                    "manifest_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="清单哈希"
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 发布清单",
                "verbose_name_plural": "Harness 发布清单",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ReleasePublication",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="发布结果 ID"
                    ),
                ),
                ("published_template_id", models.PositiveBigIntegerField(verbose_name="已发布模板 ID")),
                ("published_snapshot_id", models.PositiveBigIntegerField(verbose_name="已发布快照 ID")),
                ("published_version", models.CharField(max_length=32, verbose_name="已发布版本")),
                ("operator", models.CharField(blank=True, max_length=128, verbose_name="发布人")),
                ("publish_idempotency_ref", models.CharField(max_length=255, verbose_name="发布幂等引用")),
                (
                    "publication_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="发布结果哈希"
                    ),
                ),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="发布时间")),
            ],
            options={
                "verbose_name": "Harness 发布结果",
                "verbose_name_plural": "Harness 发布结果",
                "ordering": ["-published_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prepare_release", "Prepare release"),
                    ("publish_workflow", "Publish workflow"),
                    ("start_workflow_execution", "Start workflow execution"),
                    ("get_workflow_execution", "Get workflow execution"),
                    ("pause", "Pause"),
                    ("resume", "Resume"),
                    ("revoke", "Revoke"),
                    ("retry", "Retry"),
                    ("skip", "Skip"),
                    ("callback", "Callback"),
                    ("forced_fail", "Forced fail"),
                    ("skip_exg", "Skip exclusive gateway"),
                    ("skip_cpg", "Skip conditional parallel gateway"),
                    ("run_debug_global_real", "Run global real debug"),
                ],
                max_length=64,
                null=True,
                verbose_name="授权动作",
            ),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="action_digest",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="动作哈希"),
        ),
        migrations.AlterField(
            model_name="harnessrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("INTENT_CAPTURED", "Intent captured"),
                    ("PLANNING", "Planning"),
                    ("VALIDATING", "Validating"),
                    ("NEEDS_REPAIR", "Needs repair"),
                    ("DRAFT_READY", "Draft ready"),
                    ("DEBUGGING", "Debugging"),
                    ("RELEASE_READY", "Release ready"),
                    ("APPROVAL_PENDING", "Approval pending"),
                    ("PUBLISHING", "Publishing"),
                    ("PUBLISHED", "Published"),
                    ("EXECUTING", "Executing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("EVIDENCE_FINALIZED", "Evidence finalized"),
                ],
                max_length=32,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="permission",
            field=models.CharField(
                choices=[("MOCK", "Mock"), ("VIEW", "View"), ("EDIT", "Edit"), ("OPERATE", "Operate")],
                max_length=32,
                verbose_name="权限",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="resource_type",
            field=models.CharField(
                choices=[("TEMPLATE", "Template"), ("SCOPE", "Scope"), ("TASK", "Task")],
                max_length=32,
                verbose_name="资源类型",
            ),
        ),
        migrations.AlterField(
            model_name="tokenlease",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_leases",
                to="harness.debugsession",
                verbose_name="调试会话",
            ),
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                    ("PREPARE_RELEASE", "Prepare release"),
                    ("PUBLISH", "Publish"),
                    ("PRE_EXECUTE", "Pre execute"),
                    ("POSTCONDITION", "Postcondition"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.AddField(
            model_name="releasepublication",
            name="manifest",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication",
                to="harness.releasemanifest",
                verbose_name="发布清单",
            ),
        ),
        migrations.AddField(
            model_name="releasemanifest",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_manifests",
                to="harness.workflowplanrevision",
                verbose_name="计划修订",
            ),
        ),
        migrations.AddField(
            model_name="releasemanifest",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="release_manifests",
                to="harness.harnessrun",
                verbose_name="运行",
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="manifest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="harness.releasemanifest",
                verbose_name="发布清单",
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="harness.workflowplanrevision",
                verbose_name="计划修订",
            ),
        ),
        migrations.AddField(
            model_name="executionrun",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executions",
                to="harness.harnessrun",
                verbose_name="运行",
            ),
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="execution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_bundle",
                to="harness.executionrun",
                verbose_name="执行",
            ),
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_bundles",
                to="harness.workflowplanrevision",
                verbose_name="计划修订",
            ),
        ),
        migrations.AddField(
            model_name="evidencebundle",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_bundles",
                to="harness.harnessrun",
                verbose_name="运行",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="manifest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="harness.releasemanifest",
                verbose_name="发布清单",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="harness.workflowplanrevision",
                verbose_name="计划修订",
            ),
        ),
        migrations.AddField(
            model_name="approvalrequest",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_requests",
                to="harness.harnessrun",
                verbose_name="运行",
            ),
        ),
        migrations.AddField(
            model_name="evidenceevent",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evidence_events",
                to="harness.executionrun",
                verbose_name="流程执行",
            ),
        ),
        migrations.AddField(
            model_name="tokenlease",
            name="execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="token_leases",
                to="harness.executionrun",
                verbose_name="流程执行",
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceevent",
            constraint=models.CheckConstraint(
                check=models.Q(("debug_session__isnull", True), ("execution__isnull", True), _connector="OR"),
                name="harness_evidence_at_most_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="tokenlease",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("action__isnull", True),
                        ("action_digest__isnull", True),
                        ("execution__isnull", True),
                        ("session__isnull", False),
                    ),
                    models.Q(
                        ("action__isnull", False),
                        ("action_digest__isnull", False),
                        ("execution__isnull", False),
                        ("session__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="harness_token_lease_exact_owner_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionrun",
            constraint=models.UniqueConstraint(
                fields=("manifest", "start_idempotency_key"), name="uniq_harness_manifest_start_key"
            ),
        ),
    ]
