# Generated by Django 3.2.25 on 2026-09-05 22:30

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import bkflow.harness.models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0006_p3_release_execution"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationFeedback",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="生成反馈 ID"
                    ),
                ),
                ("plan_hash", models.CharField(max_length=64, verbose_name="计划哈希")),
                ("platform", models.CharField(max_length=64, verbose_name="平台")),
                ("platform_app", models.CharField(max_length=128, verbose_name="平台应用")),
                ("actor", models.CharField(max_length=128, verbose_name="反馈人")),
                ("space_id", models.IntegerField(db_index=True, verbose_name="空间 ID")),
                ("scope", models.CharField(max_length=255, verbose_name="授权范围")),
                ("target_environment", models.CharField(max_length=64, verbose_name="目标环境")),
                ("policy_version", models.CharField(max_length=64, verbose_name="策略版本")),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CORRECTION", "Correction"),
                            ("RUNTIME_ISSUE", "Runtime issue"),
                            ("BUSINESS_OUTCOME", "Business outcome"),
                        ],
                        max_length=32,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                ("redacted_summary", models.TextField(verbose_name="脱敏摘要")),
                (
                    "correction_artifact_ref",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="纠正工件引用"),
                ),
                ("observed_outcome", models.JSONField(blank=True, default=dict, verbose_name="观测结果")),
                ("consent_scope", models.CharField(max_length=64, verbose_name="授权用途")),
                ("idempotency_digest", models.CharField(max_length=64, verbose_name="幂等摘要")),
                (
                    "redaction_version",
                    models.CharField(default="builtin-credential-v1", max_length=64, verbose_name="脱敏版本"),
                ),
                (
                    "evidence_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_feedback",
                        to="harness.evidencebundle",
                        verbose_name="证据包",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_feedback",
                        to="harness.executionrun",
                        verbose_name="流程执行",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="harness.workflowplanrevision",
                        verbose_name="计划修订",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedback",
                        to="harness.harnessrun",
                        verbose_name="运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 生成反馈",
                "verbose_name_plural": "Harness 生成反馈",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ImprovementCandidate",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="改进候选 ID"
                    ),
                ),
                (
                    "candidate_type",
                    models.CharField(
                        choices=[
                            ("KNOWLEDGE", "Knowledge"),
                            ("REGISTRY", "Registry"),
                            ("VALIDATOR_POLICY", "Validator policy"),
                            ("PROMPT_SKILL", "Prompt or skill"),
                            ("EVAL", "Evaluation"),
                        ],
                        max_length=32,
                        verbose_name="候选类型",
                    ),
                ),
                (
                    "attribution",
                    models.CharField(
                        choices=[
                            ("REQUIREMENT", "Requirement"),
                            ("KNOWLEDGE", "Knowledge"),
                            ("PROMPT", "Prompt"),
                            ("SCHEMA", "Schema"),
                            ("RESOLVER", "Resolver"),
                            ("VALIDATOR", "Validator"),
                            ("PERMISSION", "Permission"),
                            ("PLUGIN", "Plugin"),
                            ("ENVIRONMENT", "Environment"),
                            ("POSTCONDITION", "Postcondition"),
                        ],
                        max_length=32,
                        verbose_name="归因类型",
                    ),
                ),
                ("proposal_artifact_ref", models.CharField(max_length=255, verbose_name="脱敏提案工件")),
                ("owner_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="负责人引用")),
                ("reviewer_ref", models.CharField(blank=True, max_length=128, null=True, verbose_name="审核人引用")),
                ("target_system", models.CharField(max_length=128, verbose_name="目标系统")),
                (
                    "target_tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="目标知识层级",
                    ),
                ),
                ("target_platform_key", models.CharField(blank=True, max_length=64, null=True, verbose_name="目标平台")),
                ("target_space_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="目标空间 ID")),
                ("target_scope_type", models.CharField(blank=True, max_length=64, null=True, verbose_name="目标范围类型")),
                ("target_scope_value", models.CharField(blank=True, max_length=255, null=True, verbose_name="目标范围值")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PUBLISHED", "Published"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=16,
                        verbose_name="候选状态",
                    ),
                ),
                (
                    "risk",
                    models.CharField(
                        choices=[("L0", "L0"), ("L1", "L1"), ("L2", "L2"), ("L3", "L3")],
                        max_length=2,
                        verbose_name="风险等级",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="归因置信度",
                    ),
                ),
                ("regression_case_refs", models.JSONField(blank=True, default=list, verbose_name="回归用例引用")),
                ("impact_artifact_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="影响分析工件")),
                ("rollback_artifact_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="回滚工件")),
                ("source_version", models.CharField(max_length=128, verbose_name="来源版本")),
                ("current_version", models.CharField(max_length=128, verbose_name="当前版本")),
                ("target_version", models.CharField(max_length=128, verbose_name="目标版本")),
                (
                    "promotion_receipt_digest",
                    models.CharField(blank=True, max_length=64, null=True, verbose_name="晋级回执摘要"),
                ),
                ("revision_number", models.PositiveIntegerField(default=1, verbose_name="候选修订序号")),
                (
                    "parent_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="harness.improvementcandidate",
                        verbose_name="父候选",
                    ),
                ),
                (
                    "source_evidence_bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improvement_candidates",
                        to="harness.evidencebundle",
                        verbose_name="来源证据包",
                    ),
                ),
                (
                    "source_feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="improvement_candidates",
                        to="harness.generationfeedback",
                        verbose_name="来源反馈",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 改进候选",
                "verbose_name_plural": "Harness 改进候选",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="validationreport",
            name="checkpoint",
            field=models.CharField(
                choices=[
                    ("VALIDATE", "Validate"),
                    ("DRAFT", "Draft"),
                    ("DEBUG", "Debug"),
                    ("RELEASE", "Release"),
                    ("EXECUTE", "Execute"),
                    ("START_DEBUG_SESSION", "Start debug session"),
                    ("RUN_DEBUG", "Run debug"),
                    ("PREPARE_RELEASE", "Prepare release"),
                    ("PUBLISH", "Publish"),
                    ("PRE_EXECUTE", "Pre execute"),
                    ("POSTCONDITION", "Postcondition"),
                    ("FEEDBACK_INTAKE", "Feedback intake"),
                    ("PROMOTION_EVAL", "Promotion evaluation"),
                ],
                max_length=32,
                verbose_name="检查点",
            ),
        ),
        migrations.CreateModel(
            name="HarnessEvalRun",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="评测运行 ID"
                    ),
                ),
                ("base_release_version", models.CharField(max_length=128, verbose_name="基线发布版本")),
                ("candidate_release_version", models.CharField(max_length=128, verbose_name="候选发布版本")),
                (
                    "runner_mode",
                    models.CharField(
                        choices=[("LOCAL_DETERMINISTIC", "Local deterministic"), ("SIGNED_BKAIDEV", "Signed BKAIDev")],
                        max_length=32,
                        verbose_name="Runner 模式",
                    ),
                ),
                ("package_hash", models.CharField(max_length=64, verbose_name="评测包哈希")),
                ("result_hash", models.CharField(blank=True, max_length=64, null=True, verbose_name="评测结果哈希")),
                ("signed_result_ref", models.CharField(blank=True, max_length=255, null=True, verbose_name="签名结果引用")),
                ("signed_result_digest", models.CharField(blank=True, max_length=64, null=True, verbose_name="签名结果摘要")),
                ("aggregate_metrics", models.JSONField(blank=True, default=dict, verbose_name="聚合指标")),
                (
                    "safety_result",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PASSED", "Passed"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                        verbose_name="安全结果",
                    ),
                ),
                ("threshold_snapshot", models.JSONField(default=dict, verbose_name="门禁阈值快照")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="评测状态",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("finalized_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eval_runs",
                        to="harness.improvementcandidate",
                        verbose_name="改进候选",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 评测运行",
                "verbose_name_plural": "Harness 评测运行",
                "ordering": ["-create_at"],
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="HarnessEvalCase",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="评测用例 ID"
                    ),
                ),
                ("case_id", models.CharField(max_length=128, verbose_name="用例标识")),
                ("case_version", models.CharField(max_length=64, verbose_name="用例版本")),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GLOBAL", "Global"),
                            ("PUBLIC", "Public"),
                            ("PLATFORM", "Platform"),
                            ("SPACE", "Space"),
                            ("SCOPE", "Scope"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="适用知识层级",
                    ),
                ),
                ("scope", models.CharField(max_length=255, verbose_name="适用范围")),
                ("sanitized_input_artifact_ref", models.CharField(max_length=255, verbose_name="脱敏输入工件")),
                ("expected_invariants", models.JSONField(default=dict, verbose_name="预期不变量")),
                ("scoring_schema", models.JSONField(default=dict, verbose_name="评分 Schema")),
                ("safety_tags", models.JSONField(blank=True, default=list, verbose_name="安全标签")),
                (
                    "fixture_hash",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=64, unique=True, verbose_name="Fixture 哈希"
                    ),
                ),
                (
                    "source_candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eval_cases",
                        to="harness.improvementcandidate",
                        verbose_name="来源候选",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 评测用例",
                "verbose_name_plural": "Harness 评测用例",
                "ordering": ["case_id", "case_version"],
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.CreateModel(
            name="KnowledgeCandidate",
            fields=[
                ("creator", models.CharField(blank=True, max_length=32, null=True, verbose_name="创建人")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("updated_by", models.CharField(blank=True, max_length=32, null=True, verbose_name="修改人")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, verbose_name="是否软删除")),
                (
                    "candidate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="knowledge_candidate",
                        serialize=False,
                        to="harness.improvementcandidate",
                        verbose_name="改进候选",
                    ),
                ),
                ("target_source_ref", models.TextField(verbose_name="目标知识源引用")),
                ("proposed_snapshot_lineage", models.JSONField(default=dict, verbose_name="建议快照谱系")),
                ("citation_refs", models.JSONField(blank=True, default=list, verbose_name="引用来源")),
                ("conflict_set", models.JSONField(blank=True, default=list, verbose_name="冲突引用")),
                (
                    "target_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="knowledge_candidates",
                        to="harness.knowledgesourcebinding",
                        verbose_name="目标知识绑定",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harness 知识改进候选",
                "verbose_name_plural": "Harness 知识改进候选",
                "base_manager_name": "objects",
            },
            bases=(bkflow.harness.models.AppendOnlyAggregateMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="harnessevalrun",
            constraint=models.UniqueConstraint(
                fields=("candidate", "runner_mode", "package_hash"), name="uniq_harness_eval_candidate_package"
            ),
        ),
        migrations.AddConstraint(
            model_name="harnessevalcase",
            constraint=models.UniqueConstraint(
                fields=("case_id", "case_version"), name="uniq_harness_eval_case_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="generationfeedback",
            constraint=models.UniqueConstraint(
                fields=("platform_app", "actor", "space_id", "run", "idempotency_digest"),
                name="uniq_harness_feedback_identity_digest",
            ),
        ),
    ]
