# Generated by Django 3.2.25 on 2026-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0007_p4_feedback_evalops"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="harnessidempotencyrecord",
            name="uniq_harness_idempotency_scope",
        ),
        migrations.AddField(
            model_name="harnessidempotencyrecord",
            name="scope_hash",
            field=models.CharField(editable=False, max_length=64, null=True, unique=True, verbose_name="幂等作用域摘要"),
        ),
    ]
