# Generated by Django 3.2.25 on 2026-09-28 08:53

import hashlib
import json

from django.db import IntegrityError, migrations, transaction


def backfill_scope_hash(apps, schema_editor):
    """冻结六维编码，分批回填；异常整体回滚，不删除或覆盖冲突记录。"""
    Record = apps.get_model("harness", "HarnessIdempotencyRecord")
    alias = schema_editor.connection.alias
    fields = ("platform_app", "actor", "space_id", "tool_name", "run_scope", "idempotency_key")
    records = Record.objects.using(alias)
    try:
        with transaction.atomic(using=alias):
            last_pk = 0
            while True:
                batch = list(records.filter(pk__gt=last_pk).order_by("pk").values("pk", "scope_hash", *fields)[:500])
                if not batch:
                    break
                for row in batch:
                    values = [row[field] for field in fields]
                    encoded = json.dumps(values, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
                    digest = hashlib.sha256(encoded).hexdigest()
                    if row["scope_hash"] is not None and row["scope_hash"] != digest:
                        raise RuntimeError("inconsistent idempotency scope digest; migration stopped")
                    if row["scope_hash"] is None:
                        records.filter(pk=row["pk"]).update(scope_hash=digest)
                last_pk = batch[-1]["pk"]
    except IntegrityError as error:
        raise RuntimeError("duplicate idempotency identity or digest collision; migration stopped") from error


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0008_idempotency_scope_hash"),
    ]

    operations = [
        migrations.RunPython(backfill_scope_hash, migrations.RunPython.noop),
    ]
