# Generated by Django 3.2.25 on 2026-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harness", "0009_backfill_idempotency_scope_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="harnessidempotencyrecord",
            name="scope_hash",
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name="幂等作用域摘要"),
        ),
    ]
