# Generated by Django 3.2.25 on 2025-10-14 07:11

from django.db import migrations, models

import bkflow.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0007_alter_space_app_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CredentialScope",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("credential_id", models.IntegerField(db_index=True, verbose_name="凭证ID")),
                ("scope_type", models.CharField(blank=True, max_length=128, null=True, verbose_name="作用域类型")),
                ("scope_value", models.CharField(blank=True, max_length=128, null=True, verbose_name="作用域值")),
            ],
            options={
                "verbose_name": "凭证作用域",
                "verbose_name_plural": "凭证作用域表",
            },
        ),
        migrations.AlterField(
            model_name="credential",
            name="content",
            field=bkflow.utils.models.SecretSingleJsonField(blank=True, default=dict, null=True, verbose_name="凭证内容"),
        ),
        migrations.AlterField(
            model_name="credential",
            name="type",
            field=models.CharField(
                choices=[
                    ("BK_APP", "蓝鲸应用凭证"),
                    ("BK_ACCESS_TOKEN", "蓝鲸登录态凭证"),
                    ("BASIC_AUTH", "用户名+密码"),
                    ("CUSTOM", "自定义"),
                ],
                max_length=32,
                verbose_name="凭证类型",
            ),
        ),
        migrations.AlterField(
            model_name="spaceconfig",
            name="name",
            field=models.CharField(
                choices=[
                    ("token_expiration", "Token过期时间"),
                    ("token_auto_renewal", "是否开启Token自动续期"),
                    ("engine_space_config", "引擎模块配置"),
                    ("callback_hooks", "回调配置"),
                    ("uniform_api", "API 插件配置 （如更改配置，可能对已存在数据产生不兼容影响，请谨慎操作）"),
                    ("superusers", "空间管理员"),
                    ("canvas_mode", "画布模式"),
                    ("gateway_expression", "网关表达式"),
                    ("api_gateway_credential_name", "API_GATEWAY使用的凭证配置"),
                    ("space_plugin_config", "空间插件配置"),
                ],
                max_length=32,
                verbose_name="配置项",
            ),
        ),
        migrations.AlterField(
            model_name="spaceconfig",
            name="value_type",
            field=models.CharField(
                choices=[("JSON", "JSON"), ("TEXT", "文本"), ("REF", "引用")],
                default="TEXT",
                max_length=32,
                verbose_name="配置类型",
            ),
        ),
        migrations.AddIndex(
            model_name="credentialscope",
            index=models.Index(
                fields=["credential_id", "scope_type", "scope_value"], name="space_crede_credent_6fe099_idx"
            ),
        ),
    ]
