# Generated by Django 3.2.25 on 2025-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0009_encrypt_credential_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="scope_level",
            field=models.CharField(
                choices=[("all", "空间内开放"), ("part", "设置作用域"), ("none", "不开放")],
                default="none",
                max_length=32,
                verbose_name="作用域级别",
            ),
        ),
    ]
