# Generated by Django 3.2.25 on 2026-05-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0011_set_credential_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="tenant_id",
            field=models.CharField(default="default", max_length=255, verbose_name="租户ID"),
        ),
        migrations.AddField(
            model_name="space",
            name="tenant_mode",
            field=models.CharField(
                blank=True,
                choices=[("global", "全租户模式"), ("single", "单租户模式")],
                max_length=255,
                null=True,
                verbose_name="租户模式",
            ),
        ),
        migrations.AlterField(
            model_name="spaceconfig",
            name="name",
            field=models.CharField(
                choices=[
                    ("token_expiration", "Token过期时间"),
                    ("token_auto_renewal", "是否开启Token自动续期"),
                    ("allow_multiple_triggers", "是否允许配置多个触发器"),
                    ("engine_space_config", "引擎模块配置"),
                    ("callback_hooks", "回调配置"),
                    ("uniform_api", "API 插件配置 （如更改配置，可能对已存在数据产生不兼容影响，请谨慎操作）"),
                    ("superusers", "空间管理员"),
                    ("canvas_mode", "画布模式"),
                    ("gateway_expression", "网关表达式"),
                    ("api_gateway_credential_name", "API_GATEWAY使用的凭证配置"),
                    ("space_plugin_config", "空间插件配置"),
                    ("flow_versioning", "流程版本控制"),
                ],
                max_length=32,
                verbose_name="配置项",
            ),
        ),
    ]
