# Generated by Claude Opus 4.8 on 2026-09-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0012_auto_20260512_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='用户名')),
                ('last_selected_space_id', models.IntegerField(blank=True, null=True, verbose_name='最后选择的空间ID')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='其他偏好设置')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户偏好设置 UserPreference',
                'verbose_name_plural': '用户偏好设置 UserPreference',
                'db_table': 'user_preference',
            },
        ),
    ]
