# Generated by Django 3.2.25 on 2026-09-28 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0012_auto_20260512_1102"),
        ("space", "0012_expand_config_name_for_harness_p4"),
    ]

    operations = []
