# Generated by Django 3.2.25 on 2026-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0013_merge_20260928_1623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spaceconfig",
            name="name",
            field=models.CharField(
                choices=[
                    ("token_expiration", "Token过期时间"),
                    ("token_auto_renewal", "Token自动续期"),
                    ("allow_multiple_triggers", "是否允许配置多个触发器"),
                    ("engine_space_config", "引擎模块配置"),
                    ("callback_hooks", "回调配置"),
                    ("uniform_api", "API插件"),
                    ("superusers", "空间管理员"),
                    ("canvas_mode", "画布模式"),
                    ("gateway_expression", "网关表达式"),
                    ("api_gateway_credential_name", "网关凭证"),
                    ("space_plugin_config", "空间插件配置"),
                    ("flow_versioning", "流程版本控制"),
                    ("harness_enabled", "是否启用 AI 流程生成 Harness"),
                    ("harness_knowledge_router_enabled", "是否启用 AI 流程生成 Harness 知识检索"),
                    ("harness_debug_enabled", "是否启用 AI 流程生成 Harness 调试"),
                    ("harness_real_step_enabled", "是否启用 AI 流程生成 Harness 真实单步调试"),
                    ("harness_publish_enabled", "是否启用 AI 流程生成 Harness 发布"),
                    ("harness_execution_enabled", "是否启用 AI 流程生成 Harness 流程执行"),
                    ("harness_global_real_enabled", "是否启用 AI 流程生成 Harness 全局真实调试"),
                    ("harness_feedback_enabled", "是否启用 AI 流程生成 Harness 反馈摄入"),
                    ("harness_candidate_promotion_enabled", "是否启用 AI 流程生成 Harness 候选晋级"),
                    ("harness_deployment", "AI 流程生成 Harness 可信部署绑定"),
                ],
                max_length=64,
                verbose_name="配置项",
            ),
        ),
    ]
