# Generated by Django 3.2.15 on 2024-09-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_taskoperationrecord_instance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmockdata',
            name='mock_data_ids',
            field=models.JSONField(default=dict, verbose_name='task mock data ids'),
        ),
    ]
