# Generated by Django 3.2.15 on 2025-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0010_enginespaceconfig"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enginespaceconfig",
            name="example",
        ),
        migrations.AddField(
            model_name="enginespaceconfig",
            name="space_id",
            field=models.BigIntegerField(default=0, verbose_name="空间id"),
            preserve_default=False,
        ),
    ]
