# Generated by Django 3.2.15 on 2025-08-15 11:22

import django.db.models.deletion
import pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("task", "0010_enginespaceconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, verbose_name="周期任务名称")),
                ("template_id", models.IntegerField(db_index=True, verbose_name="关联流程模板 ID")),
                ("trigger_id", models.IntegerField(db_index=True, verbose_name="关联触发器 ID")),
                ("cron", models.CharField(max_length=128, verbose_name="调度策略")),
                ("config", models.JSONField(help_text="流程相关信息")),
                ("total_run_count", models.PositiveIntegerField(default=0, verbose_name="执行次数")),
                ("last_run_at", models.DateTimeField(null=True, verbose_name="上次运行时间")),
                ("creator", models.CharField(default="", max_length=32, verbose_name="创建者")),
                ("extra_info", pipeline.models.CompressJSONField(null=True, verbose_name="额外信息")),
                (
                    "celery_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodic_task",
                        to="django_celery_beat.periodictask",
                        verbose_name="celery 周期任务实例",
                    ),
                ),
            ],
            options={
                "verbose_name": "周期任务",
                "verbose_name_plural": "周期任务",
            },
        ),
    ]
