# Generated by Django 3.2.15 on 2025-08-20 05:00

from django.db import migrations, models

import bkflow.task.models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0011_periodictask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodictask",
            name="cron",
            field=models.JSONField(default=bkflow.task.models.default_cron, verbose_name="调度策略"),
        ),
        migrations.AlterField(
            model_name="periodictask",
            name="extra_info",
            field=models.JSONField(null=True, verbose_name="额外信息"),
        ),
    ]
