# Generated by Django 3.2.25 on 2025-08-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0012_auto_20250820_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="trigger_method",
            field=models.CharField(default="manual", max_length=32, verbose_name="触发方式"),
        ),
    ]
