# Generated by Django 3.2.25 on 2025-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0013_taskinstance_trigger_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskFlowRelation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.BigIntegerField(db_index=True, verbose_name="任务ID")),
                ("parent_task_id", models.BigIntegerField(db_index=True, verbose_name="父任务ID")),
                ("root_task_id", models.BigIntegerField(db_index=True, verbose_name="根任务ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("extra_info", models.JSONField(null=True, verbose_name="额外信息")),
            ],
            options={
                "verbose_name": "任务关系",
                "verbose_name_plural": "任务关系",
            },
        ),
    ]
