# Generated by Django 3.2.25 on 2025-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_taskflowrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasktreeinfo',
            options={'ordering': ['-id'], 'verbose_name': '任务流程树信息', 'verbose_name_plural': '任务流程树信息'},
        ),
        migrations.CreateModel(
            name='TaskLabelRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(db_index=True, verbose_name='任务ID')),
                ('label_id', models.IntegerField(db_index=True, verbose_name='标签ID')),
            ],
            options={
                'verbose_name': '任务标签关系 TaskLabelRelation',
                'verbose_name_plural': '任务标签关系 TaskLabelRelation',
                'unique_together': {('task_id', 'label_id')},
            },
        ),
    ]
