# Generated by Django 3.2.25 on 2026-05-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0015_auto_20251204_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinstance",
            name="tenant_id",
            field=models.CharField(default="default", max_length=255, verbose_name="租户ID"),
        ),
    ]
