# Generated by Django 3.2.25 on 2026-06-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0015_auto_20251204_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskinstance",
            name="create_method",
            field=models.CharField(
                choices=[("API", "API"), ("MOCK", "MOCK"), ("DEBUG", "DEBUG")],
                default="API",
                max_length=32,
                verbose_name="创建方式",
            ),
        ),
    ]
