# Generated by Django 3.2.25 on 2026-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0016_open_plugin_run_callback_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openpluginruncallbackref",
            name="node_version",
            field=models.CharField(blank=True, default="", max_length=64, verbose_name="节点版本"),
        ),
        migrations.AlterField(
            model_name="taskoperationrecord",
            name="operate_type",
            field=models.CharField(
                choices=[
                    ("create", "创建"),
                    ("delete", "删除"),
                    ("update", "修改"),
                    ("start", "执行"),
                    ("pause", "暂停"),
                    ("resume", "继续"),
                    ("revoke", "撤消"),
                    ("callback", "回调"),
                    ("retry", "重试"),
                    ("loop_retry", "循环重试"),
                    ("skip", "跳过"),
                    ("loop_skip", "循环跳过"),
                    ("skip_exg", "跳过失败网关"),
                    ("skip_cpg", "跳过并行条件网关"),
                    ("pause_subproc", "暂停节点"),
                    ("resume_subproc", "继续节点"),
                    ("forced_fail", "强制失败"),
                    ("task_action", "任务操作"),
                    ("nodes_action", "节点操作"),
                ],
                max_length=64,
                verbose_name="操作类型",
            ),
        ),
    ]
