# Generated by Django 3.2.25 on 2026-08-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0016_auto_20260626_1306"),
        ("task", "0017_widen_open_plugin_callback_node_version"),
    ]

    operations = []
