# Generated by Django 3.2.25 on 2026-07-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0017_merge_20260706_1507"),
        ("task", "0017_widen_open_plugin_callback_node_version"),
    ]

    operations = []
