# Generated by Django 3.2.25 on 2026-09-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0016_taskinstance_tenant_id"),
        ("task", "0018_merge_20260819_1508"),
    ]

    operations = []
